export const DATA_SOURCES = {
  Firm: {
    label: "Firms",
    fields: [
      { key: "name", label: "Firm Name", type: "text" },
      { key: "firm_types", label: "Firm Types", type: "array" },
      { key: "website", label: "Website", type: "text" },
      { key: "linkedin_url", label: "LinkedIn URL", type: "text" },
      { key: "year_founded", label: "Year Founded", type: "number" },
      { key: "description", label: "Description", type: "text" },
      { key: "addresses", label: "Addresses", type: "object" },
      { key: "phones", label: "Phone Numbers", type: "object" },
    ],
  },
  Contact: {
    label: "Contacts",
    fields: [
      { key: "salutation", label: "Salutation", type: "text" },
      { key: "first_name", label: "First Name", type: "text" },
      { key: "last_name", label: "Last Name", type: "text" },
      { key: "title", label: "Job Title", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "phones", label: "Phone Numbers", type: "object" },
      { key: "addresses", label: "Addresses", type: "object" },
      { key: "contact_type", label: "Contact Type", type: "text" },
      { key: "contact_roles", label: "Roles", type: "array" },
      { key: "contact_status", label: "Status", type: "text" },
      { key: "employee_status", label: "Employee Status", type: "text" },
      { key: "firm_ids", label: "Associated Firms", type: "array" },
      { key: "gender", label: "Gender", type: "text" },
      { key: "ethnicity", label: "Ethnicity", type: "array" },
    ],
  },
  Product: {
    label: "Products",
    fields: [
      { key: "name", label: "Product Name", type: "text" },
      { key: "description", label: "Description", type: "text" },
      { key: "product_type", label: "Product Type", type: "text" },
      { key: "firm_name", label: "Firm Name", type: "text" },
      { key: "asset_class", label: "Asset Class", type: "text" },
      { key: "geography", label: "Geography", type: "text" },
      { key: "market_cap", label: "Market Cap", type: "text" },
      { key: "style", label: "Style", type: "text" },
      { key: "investment_process", label: "Investment Process", type: "text" },
      { key: "implementation_process", label: "Implementation", type: "text" },
      { key: "aapryl_style", label: "Aapryl Style", type: "text" },
    ],
  },
  Portfolio: {
    label: "Portfolios",
    fields: [
      { key: "portfolio_name", label: "Portfolio Name", type: "text" },
      { key: "allocator_name", label: "Allocator", type: "text" },
      { key: "advisor_type", label: "Advisor Type", type: "text" },
      { key: "advisor_firm_name", label: "Advisor Firm", type: "text" },
      { key: "inception_date", label: "Inception Date", type: "date" },
      { key: "advisor_inception_date", label: "Advisor Inception", type: "date" },
    ],
  },
  Benchmark: {
    label: "Benchmarks",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "asset_class", label: "Asset Class", type: "text" },
      { key: "region", label: "Region", type: "text" },
      { key: "market_capitalization", label: "Market Cap", type: "text" },
      { key: "style", label: "Style", type: "text" },
      { key: "inception_date", label: "Inception Date", type: "date" },
      { key: "description", label: "Description", type: "text" },
    ],
  },
  ContactActivity: {
    label: "Activities",
    fields: [
      { key: "activity_type", label: "Activity Type", type: "text" },
      { key: "activity_date", label: "Activity Date", type: "date" },
      { key: "subjects", label: "Subjects", type: "array" },
      { key: "notes", label: "Notes", type: "text" },
    ],
  },
  FollowUpTask: {
    label: "Tasks",
    fields: [
      { key: "due_date", label: "Due Date", type: "date" },
      { key: "task_description", label: "Description", type: "text" },
      { key: "status", label: "Status", type: "text" },
      { key: "assigned_to_contact_name", label: "Assigned To", type: "text" },
      { key: "assigned_to_firm_name", label: "Assigned Firm", type: "text" },
      { key: "originator_contact_name", label: "Originator", type: "text" },
      { key: "completion_date", label: "Completion Date", type: "date" },
    ],
  },
};

export const COMPUTATION_TYPES = [
  { value: "count", label: "Count", needsField: false },
  { value: "sum", label: "Sum", needsField: true, numericOnly: true },
  { value: "average", label: "Average", needsField: true, numericOnly: true },
  { value: "min", label: "Minimum", needsField: true, numericOnly: true },
  { value: "max", label: "Maximum", needsField: true, numericOnly: true },
  { value: "percentage", label: "Percentage Distribution", needsField: false },
  { value: "growth", label: "Growth Rate", needsField: true, numericOnly: true },
];

export const CHART_TYPES = [
  { value: "bar", label: "Bar Chart" },
  { value: "line", label: "Line Chart" },
  { value: "pie", label: "Pie Chart" },
  { value: "area", label: "Area Chart" },
  { value: "scatter", label: "Scatter Plot" },
];

export const OUTPUT_FORMATS = [
  { value: "pdf", label: "PDF Download" },
  { value: "csv", label: "CSV Export" },
  { value: "print", label: "Print" },
];

export const STANDARD_REPORTS = [
  {
    id: "firm-directory",
    name: "Firm Directory",
    description: "Complete listing of all firms with type, website, and founding year",
    config: {
      name: "Firm Directory",
      description: "Complete listing of all firms with type, website, and founding year",
      data_source: "Firm",
      selected_fields: ["name", "firm_types", "website", "year_founded"],
      computations: [],
      format_type: "table",
      sort_by: "name",
      sort_order: "asc",
      output_formats: ["pdf", "csv", "print"],
      page_orientation: "landscape",
      include_summary: true,
    },
  },
  {
    id: "contact-directory",
    name: "Contact Directory",
    description: "All contacts with name, title, email, and contact type",
    config: {
      name: "Contact Directory",
      description: "All contacts with name, title, email, and contact type",
      data_source: "Contact",
      selected_fields: ["first_name", "last_name", "title", "email", "contact_type", "contact_status"],
      computations: [],
      format_type: "table",
      sort_by: "last_name",
      sort_order: "asc",
      output_formats: ["pdf", "csv", "print"],
      page_orientation: "landscape",
      include_summary: true,
    },
  },
  {
    id: "product-summary",
    name: "Product Summary",
    description: "All products with firm, type, asset class, and style",
    config: {
      name: "Product Summary",
      description: "All products with firm, type, asset class, and style",
      data_source: "Product",
      selected_fields: ["name", "product_type", "firm_name", "asset_class", "geography", "style"],
      computations: [],
      format_type: "table",
      sort_by: "name",
      sort_order: "asc",
      output_formats: ["pdf", "csv", "print"],
      page_orientation: "landscape",
      include_summary: true,
    },
  },
  {
    id: "portfolio-overview",
    name: "Portfolio Overview",
    description: "All portfolios with allocator, advisor, and inception dates",
    config: {
      name: "Portfolio Overview",
      description: "All portfolios with allocator, advisor, and inception dates",
      data_source: "Portfolio",
      selected_fields: ["portfolio_name", "allocator_name", "advisor_type", "advisor_firm_name", "inception_date"],
      computations: [],
      format_type: "table",
      sort_by: "portfolio_name",
      sort_order: "asc",
      output_formats: ["pdf", "csv", "print"],
      page_orientation: "landscape",
      include_summary: true,
    },
  },
  {
    id: "activity-summary",
    name: "Activity Summary",
    description: "Count of activities by type with breakdown by date",
    config: {
      name: "Activity Summary",
      description: "Count of activities by type with breakdown by date",
      data_source: "ContactActivity",
      selected_fields: ["activity_type", "activity_date", "subjects"],
      computations: [
        { type: "count", group_by: "activity_type", label: "Activities by Type" },
      ],
      format_type: "mixed",
      chart_type: "bar",
      group_by: "activity_type",
      sort_by: "activity_date",
      sort_order: "desc",
      output_formats: ["pdf", "print"],
      page_orientation: "landscape",
      include_summary: true,
    },
  },
  {
    id: "task-status-report",
    name: "Task Status Report",
    description: "Task status breakdown by assignee with due dates",
    config: {
      name: "Task Status Report",
      description: "Task status breakdown by assignee with due dates",
      data_source: "FollowUpTask",
      selected_fields: ["due_date", "task_description", "status", "assigned_to_contact_name", "assigned_to_firm_name"],
      computations: [
        { type: "count", group_by: "status", label: "Tasks by Status" },
      ],
      format_type: "mixed",
      chart_type: "pie",
      group_by: "status",
      sort_by: "due_date",
      sort_order: "asc",
      output_formats: ["pdf", "print"],
      page_orientation: "landscape",
      include_summary: true,
    },
  },
  {
    id: "benchmark-summary",
    name: "Benchmark Summary",
    description: "All benchmarks with asset class, region, and style",
    config: {
      name: "Benchmark Summary",
      description: "All benchmarks with asset class, region, and style",
      data_source: "Benchmark",
      selected_fields: ["name", "asset_class", "region", "market_capitalization", "style", "inception_date"],
      computations: [],
      format_type: "table",
      sort_by: "name",
      sort_order: "asc",
      output_formats: ["pdf", "csv", "print"],
      page_orientation: "landscape",
      include_summary: true,
    },
  },
];