// Geographic data: countries, states/provinces, cities, and zip code lookup

export const COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "United Kingdom" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "JP", name: "Japan" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "CH", name: "Switzerland" },
  { code: "NL", name: "Netherlands" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "IE", name: "Ireland" },
  { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" },
  { code: "PT", name: "Portugal" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "IN", name: "India" },
  { code: "CN", name: "China" },
  { code: "KR", name: "South Korea" },
  { code: "NZ", name: "New Zealand" },
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CV", name: "Cape Verde" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (DRC)" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IL", name: "Israel" },
  { code: "JM", name: "Jamaica" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "North Korea" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

// Comprehensive states/provinces for all countries live in statesData.js
// (ISO 3166-2). Re-exported here so existing imports keep working.
import {
  STATES_BY_COUNTRY as FULL_STATES_BY_COUNTRY,
  getStatesForCountryCode,
  getStateName,
} from "./statesData";
export { getStatesForCountryCode, getStateName };
export const STATES_BY_COUNTRY = FULL_STATES_BY_COUNTRY;

// Cities by state (US only - most common cities per state)
export const CITIES_BY_STATE = {
  AL: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
  AK: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
  AZ: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Tempe", "Gilbert", "Peoria"],
  AR: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
  CA: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento", "Oakland", "Irvine", "Santa Ana", "Anaheim", "Riverside", "Fresno", "Long Beach", "Bakersfield", "Pasadena", "San Bernardino"],
  CO: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Boulder", "Arvada", "Westminster"],
  CT: ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury", "Norwalk", "Greenwich"],
  DE: ["Wilmington", "Dover", "Newark", "Middletown"],
  FL: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Fort Lauderdale", "Tallahassee", "Cape Coral", "Hialeah", "Pembroke Pines", "Hollywood", "Boca Raton", "Naples", "Sarasota"],
  GA: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens", "Sandy Springs", "Macon", "Alpharetta"],
  HI: ["Honolulu", "Hilo", "Kailua", "Kapolei", "Kaneohe"],
  ID: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
  IL: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield", "Peoria", "Elgin"],
  IN: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Bloomington"],
  IA: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
  KS: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
  KY: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
  LA: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
  ME: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
  MD: ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie", "Annapolis", "Silver Spring", "Bethesda"],
  MA: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Quincy", "Lynn", "Newton", "Somerville"],
  MI: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Flint", "Dearborn"],
  MN: ["Minneapolis", "St. Paul", "Rochester", "Bloomington", "Duluth", "Brooklyn Park", "Plymouth", "Edina"],
  MS: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
  MO: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit"],
  MT: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
  NE: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  NV: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
  NH: ["Manchester", "Nashua", "Concord", "Derry", "Dover"],
  NJ: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Woodbridge", "Lakewood", "Trenton", "Princeton"],
  NM: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
  NY: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "White Plains", "Utica", "Schenectady"],
  NC: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "Asheville"],
  ND: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
  OH: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
  OK: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
  OR: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Bend"],
  PA: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton", "Bethlehem", "Lancaster", "Harrisburg"],
  RI: ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence"],
  SC: ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Greenville"],
  SD: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"],
  TN: ["Memphis", "Nashville", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin"],
  TX: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Lubbock", "Irving", "Laredo", "Garland", "Frisco", "McKinney"],
  UT: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy"],
  VT: ["Burlington", "Rutland", "South Burlington", "Essex Junction"],
  VA: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton", "Roanoke", "McLean", "Arlington"],
  WA: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kirkland", "Redmond", "Renton", "Everett"],
  WV: ["Charleston", "Huntington", "Morgantown", "Parkersburg"],
  WI: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton"],
  WY: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
  DC: ["Washington"],
};

// Simple US zip code prefix → city/state lookup
const ZIP_PREFIX_DATA = {
  "100": { city: "New York City", state: "NY" },
  "101": { city: "New York City", state: "NY" },
  "102": { city: "New York City", state: "NY" },
  "103": { city: "Staten Island", state: "NY" },
  "104": { city: "Bronx", state: "NY" },
  "105": { city: "White Plains", state: "NY" },
  "106": { city: "White Plains", state: "NY" },
  "107": { city: "Yonkers", state: "NY" },
  "110": { city: "Jamaica", state: "NY" },
  "111": { city: "Long Island City", state: "NY" },
  "112": { city: "Brooklyn", state: "NY" },
  "113": { city: "Flushing", state: "NY" },
  "114": { city: "Jamaica", state: "NY" },
  "115": { city: "Hicksville", state: "NY" },
  "116": { city: "Hicksville", state: "NY" },
  "117": { city: "Smithtown", state: "NY" },
  "118": { city: "Patchogue", state: "NY" },
  "119": { city: "Southampton", state: "NY" },
  "120": { city: "Albany", state: "NY" },
  "121": { city: "Albany", state: "NY" },
  "122": { city: "Albany", state: "NY" },
  "130": { city: "Syracuse", state: "NY" },
  "140": { city: "Buffalo", state: "NY" },
  "141": { city: "Buffalo", state: "NY" },
  "150": { city: "Pittsburgh", state: "PA" },
  "151": { city: "Pittsburgh", state: "PA" },
  "152": { city: "Pittsburgh", state: "PA" },
  "191": { city: "Philadelphia", state: "PA" },
  "192": { city: "Philadelphia", state: "PA" },
  "021": { city: "Boston", state: "MA" },
  "022": { city: "Boston", state: "MA" },
  "023": { city: "Boston", state: "MA" },
  "024": { city: "Boston", state: "MA" },
  "302": { city: "Atlanta", state: "GA" },
  "303": { city: "Atlanta", state: "GA" },
  "331": { city: "Miami", state: "FL" },
  "332": { city: "Miami", state: "FL" },
  "336": { city: "Tampa", state: "FL" },
  "328": { city: "Orlando", state: "FL" },
  "441": { city: "Cleveland", state: "OH" },
  "432": { city: "Columbus", state: "OH" },
  "481": { city: "Detroit", state: "MI" },
  "606": { city: "Chicago", state: "IL" },
  "607": { city: "Chicago", state: "IL" },
  "550": { city: "Minneapolis", state: "MN" },
  "551": { city: "St. Paul", state: "MN" },
  "631": { city: "St. Louis", state: "MO" },
  "641": { city: "Kansas City", state: "MO" },
  "700": { city: "New Orleans", state: "LA" },
  "701": { city: "New Orleans", state: "LA" },
  "770": { city: "Houston", state: "TX" },
  "752": { city: "Dallas", state: "TX" },
  "787": { city: "Austin", state: "TX" },
  "782": { city: "San Antonio", state: "TX" },
  "800": { city: "Denver", state: "CO" },
  "802": { city: "Denver", state: "CO" },
  "850": { city: "Phoenix", state: "AZ" },
  "852": { city: "Phoenix", state: "AZ" },
  "900": { city: "Los Angeles", state: "CA" },
  "901": { city: "Los Angeles", state: "CA" },
  "902": { city: "Los Angeles", state: "CA" },
  "919": { city: "San Diego", state: "CA" },
  "921": { city: "San Diego", state: "CA" },
  "941": { city: "San Francisco", state: "CA" },
  "942": { city: "Sacramento", state: "CA" },
  "946": { city: "Oakland", state: "CA" },
  "980": { city: "Seattle", state: "WA" },
  "981": { city: "Seattle", state: "WA" },
  "971": { city: "Portland", state: "OR" },
  "972": { city: "Portland", state: "OR" },
  "890": { city: "Las Vegas", state: "NV" },
  "891": { city: "Las Vegas", state: "NV" },
  "841": { city: "Salt Lake City", state: "UT" },
  "842": { city: "Salt Lake City", state: "UT" },
  "372": { city: "Nashville", state: "TN" },
  "380": { city: "Memphis", state: "TN" },
  "282": { city: "Charlotte", state: "NC" },
  "275": { city: "Raleigh", state: "NC" },
  "681": { city: "Omaha", state: "NE" },
  "531": { city: "Milwaukee", state: "WI" },
  "064": { city: "Stamford", state: "CT" },
  "068": { city: "Greenwich", state: "CT" },
  "070": { city: "Newark", state: "NJ" },
  "071": { city: "Newark", state: "NJ" },
  "074": { city: "Princeton", state: "NJ" },
  "077": { city: "Jersey City", state: "NJ" },
  "200": { city: "Washington", state: "DC" },
  "201": { city: "Washington", state: "DC" },
  "202": { city: "Washington", state: "DC" },
  "203": { city: "Washington", state: "DC" },
  "204": { city: "Washington", state: "DC" },
  "220": { city: "Arlington", state: "VA" },
  "221": { city: "Alexandria", state: "VA" },
  "222": { city: "Arlington", state: "VA" },
  "207": { city: "Bethesda", state: "MD" },
  "208": { city: "Rockville", state: "MD" },
  "212": { city: "Baltimore", state: "MD" },
};

export function lookupZipCode(zip) {
  if (!zip || zip.length < 3) return null;
  const prefix = zip.substring(0, 3);
  return ZIP_PREFIX_DATA[prefix] || null;
}

export function getStatesForCountry(countryCode) {
  return STATES_BY_COUNTRY[countryCode] || [];
}

// Resolve a state code to its display name for the given country.
export function getStateDisplayName(countryCode, stateCode) {
  return getStateName(countryCode, stateCode);
}

export function getCitiesForState(stateCode) {
  return CITIES_BY_STATE[stateCode] || [];
}

export function getAreaCodesForCity(city) {
  // Map common US cities to their primary area codes
  const cityAreaCodes = {
    "New York City": [{ code: "212", label: "212 - Manhattan" }, { code: "718", label: "718 - Outer Boroughs" }, { code: "347", label: "347 - Manhattan Overlay" }],
    "Los Angeles": [{ code: "213", label: "213 - Central LA" }, { code: "310", label: "310 - West LA" }, { code: "424", label: "424 - LA Overlay" }],
    "Chicago": [{ code: "312", label: "312 - Downtown Chicago" }, { code: "773", label: "773 - North/West Chicago" }, { code: "872", label: "872 - Chicago Overlay" }],
    "Houston": [{ code: "713", label: "713 - Houston" }, { code: "281", label: "281 - Surrounding" }, { code: "832", label: "832 - Houston Overlay" }],
    "Phoenix": [{ code: "602", label: "602 - Phoenix" }, { code: "480", label: "480 - East Valley" }],
    "Philadelphia": [{ code: "215", label: "215 - Philadelphia" }, { code: "267", label: "267 - Philadelphia Overlay" }],
    "San Antonio": [{ code: "210", label: "210 - San Antonio" }, { code: "737", label: "737 - San Antonio Overlay" }],
    "San Diego": [{ code: "619", label: "619 - Downtown SD" }, { code: "858", label: "858 - North County" }],
    "Dallas": [{ code: "214", label: "214 - Dallas" }, { code: "972", label: "972 - Metroplex" }, { code: "469", label: "469 - Dallas Overlay" }],
    "San Jose": [{ code: "408", label: "408 - San Jose" }, { code: "669", label: "669 - San Jose Overlay" }],
    "Austin": [{ code: "512", label: "512 - Austin" }, { code: "737", label: "737 - Austin Overlay" }],
    "Miami": [{ code: "305", label: "305 - Miami" }, { code: "786", label: "786 - Miami Overlay" }],
    "Denver": [{ code: "303", label: "303 - Denver" }, { code: "720", label: "720 - Denver Overlay" }],
    "Seattle": [{ code: "206", label: "206 - Seattle" }, { code: "425", label: "425 - Eastside" }],
    "Boston": [{ code: "617", label: "617 - Boston" }, { code: "857", label: "857 - Boston Overlay" }],
    "Atlanta": [{ code: "404", label: "404 - Atlanta" }, { code: "770", label: "770 - Metro Atlanta" }, { code: "678", label: "678 - Overlay" }],
    "Washington": [{ code: "202", label: "202 - Washington DC" }, { code: "703", label: "703 - Northern Virginia" }, { code: "571", label: "571 - Overlay" }],
  };
  return cityAreaCodes[city] || [];
}