// Geographic data: countries, states/provinces, cities, and zip code lookup

export const COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "United Kingdom" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "JP", name: "Japan" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "CH", name: "Switzerland" },
  { code: "NL", name: "Netherlands" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "IE", name: "Ireland" },
  { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" },
  { code: "PT", name: "Portugal" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "IN", name: "India" },
  { code: "CN", name: "China" },
  { code: "KR", name: "South Korea" },
  { code: "NZ", name: "New Zealand" },
];

export const STATES_BY_COUNTRY = {
  US: [
    { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" }, { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" }, { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" }, { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" }, { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" }, { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" }, { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" },
    { code: "DC", name: "District of Columbia" },
  ],
  CA: [
    { code: "AB", name: "Alberta" }, { code: "BC", name: "British Columbia" },
    { code: "MB", name: "Manitoba" }, { code: "NB", name: "New Brunswick" },
    { code: "NL", name: "Newfoundland and Labrador" }, { code: "NS", name: "Nova Scotia" },
    { code: "NT", name: "Northwest Territories" }, { code: "NU", name: "Nunavut" },
    { code: "ON", name: "Ontario" }, { code: "PE", name: "Prince Edward Island" },
    { code: "QC", name: "Quebec" }, { code: "SK", name: "Saskatchewan" },
    { code: "YT", name: "Yukon" },
  ],
  AU: [
    { code: "ACT", name: "Australian Capital Territory" },
    { code: "NSW", name: "New South Wales" },
    { code: "NT", name: "Northern Territory" },
    { code: "QLD", name: "Queensland" },
    { code: "SA", name: "South Australia" },
    { code: "TAS", name: "Tasmania" },
    { code: "VIC", name: "Victoria" },
    { code: "WA", name: "Western Australia" },
  ],
  GB: [
    { code: "ENG", name: "England" }, { code: "SCT", name: "Scotland" },
    { code: "WLS", name: "Wales" }, { code: "NIR", name: "Northern Ireland" },
  ],
  DE: [
    { code: "BB", name: "Brandenburg" }, { code: "BE", name: "Berlin" },
    { code: "BW", name: "Baden-Württemberg" }, { code: "BY", name: "Bavaria" },
    { code: "HB", name: "Bremen" }, { code: "HE", name: "Hesse" },
    { code: "HH", name: "Hamburg" }, { code: "MV", name: "Mecklenburg-Vorpommern" },
    { code: "NI", name: "Lower Saxony" }, { code: "NW", name: "North Rhine-Westphalia" },
    { code: "RP", name: "Rhineland-Palatinate" }, { code: "SH", name: "Schleswig-Holstein" },
    { code: "SL", name: "Saarland" }, { code: "SN", name: "Saxony" },
    { code: "ST", name: "Saxony-Anhalt" }, { code: "TH", name: "Thuringia" },
  ],
};

// Cities by state (US only - most common cities per state)
export const CITIES_BY_STATE = {
  AL: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
  AK: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
  AZ: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Tempe", "Gilbert", "Peoria"],
  AR: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
  CA: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento", "Oakland", "Irvine", "Santa Ana", "Anaheim", "Riverside", "Fresno", "Long Beach", "Bakersfield", "Pasadena", "San Bernardino"],
  CO: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Boulder", "Arvada", "Westminster"],
  CT: ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury", "Norwalk", "Greenwich"],
  DE: ["Wilmington", "Dover", "Newark", "Middletown"],
  FL: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Fort Lauderdale", "Tallahassee", "Cape Coral", "Hialeah", "Pembroke Pines", "Hollywood", "Boca Raton", "Naples", "Sarasota"],
  GA: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens", "Sandy Springs", "Macon", "Alpharetta"],
  HI: ["Honolulu", "Hilo", "Kailua", "Kapolei", "Kaneohe"],
  ID: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
  IL: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield", "Peoria", "Elgin"],
  IN: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Bloomington"],
  IA: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
  KS: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
  KY: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
  LA: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
  ME: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
  MD: ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie", "Annapolis", "Silver Spring", "Bethesda"],
  MA: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Quincy", "Lynn", "Newton", "Somerville"],
  MI: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Flint", "Dearborn"],
  MN: ["Minneapolis", "St. Paul", "Rochester", "Bloomington", "Duluth", "Brooklyn Park", "Plymouth", "Edina"],
  MS: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
  MO: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit"],
  MT: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
  NE: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  NV: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
  NH: ["Manchester", "Nashua", "Concord", "Derry", "Dover"],
  NJ: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Woodbridge", "Lakewood", "Trenton", "Princeton"],
  NM: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
  NY: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "White Plains", "Utica", "Schenectady"],
  NC: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "Asheville"],
  ND: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
  OH: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
  OK: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
  OR: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Bend"],
  PA: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton", "Bethlehem", "Lancaster", "Harrisburg"],
  RI: ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence"],
  SC: ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Greenville"],
  SD: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"],
  TN: ["Memphis", "Nashville", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin"],
  TX: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Lubbock", "Irving", "Laredo", "Garland", "Frisco", "McKinney"],
  UT: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy"],
  VT: ["Burlington", "Rutland", "South Burlington", "Essex Junction"],
  VA: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton", "Roanoke", "McLean", "Arlington"],
  WA: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kirkland", "Redmond", "Renton", "Everett"],
  WV: ["Charleston", "Huntington", "Morgantown", "Parkersburg"],
  WI: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton"],
  WY: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
  DC: ["Washington"],
};

// Simple US zip code prefix → city/state lookup
const ZIP_PREFIX_DATA = {
  "100": { city: "New York City", state: "NY" },
  "101": { city: "New York City", state: "NY" },
  "102": { city: "New York City", state: "NY" },
  "103": { city: "Staten Island", state: "NY" },
  "104": { city: "Bronx", state: "NY" },
  "105": { city: "White Plains", state: "NY" },
  "106": { city: "White Plains", state: "NY" },
  "107": { city: "Yonkers", state: "NY" },
  "110": { city: "Jamaica", state: "NY" },
  "111": { city: "Long Island City", state: "NY" },
  "112": { city: "Brooklyn", state: "NY" },
  "113": { city: "Flushing", state: "NY" },
  "114": { city: "Jamaica", state: "NY" },
  "115": { city: "Hicksville", state: "NY" },
  "116": { city: "Hicksville", state: "NY" },
  "117": { city: "Smithtown", state: "NY" },
  "118": { city: "Patchogue", state: "NY" },
  "119": { city: "Southampton", state: "NY" },
  "120": { city: "Albany", state: "NY" },
  "121": { city: "Albany", state: "NY" },
  "122": { city: "Albany", state: "NY" },
  "130": { city: "Syracuse", state: "NY" },
  "140": { city: "Buffalo", state: "NY" },
  "141": { city: "Buffalo", state: "NY" },
  "150": { city: "Pittsburgh", state: "PA" },
  "151": { city: "Pittsburgh", state: "PA" },
  "152": { city: "Pittsburgh", state: "PA" },
  "191": { city: "Philadelphia", state: "PA" },
  "192": { city: "Philadelphia", state: "PA" },
  "021": { city: "Boston", state: "MA" },
  "022": { city: "Boston", state: "MA" },
  "023": { city: "Boston", state: "MA" },
  "024": { city: "Boston", state: "MA" },
  "302": { city: "Atlanta", state: "GA" },
  "303": { city: "Atlanta", state: "GA" },
  "331": { city: "Miami", state: "FL" },
  "332": { city: "Miami", state: "FL" },
  "336": { city: "Tampa", state: "FL" },
  "328": { city: "Orlando", state: "FL" },
  "441": { city: "Cleveland", state: "OH" },
  "432": { city: "Columbus", state: "OH" },
  "481": { city: "Detroit", state: "MI" },
  "606": { city: "Chicago", state: "IL" },
  "607": { city: "Chicago", state: "IL" },
  "550": { city: "Minneapolis", state: "MN" },
  "551": { city: "St. Paul", state: "MN" },
  "631": { city: "St. Louis", state: "MO" },
  "641": { city: "Kansas City", state: "MO" },
  "700": { city: "New Orleans", state: "LA" },
  "701": { city: "New Orleans", state: "LA" },
  "770": { city: "Houston", state: "TX" },
  "752": { city: "Dallas", state: "TX" },
  "787": { city: "Austin", state: "TX" },
  "782": { city: "San Antonio", state: "TX" },
  "800": { city: "Denver", state: "CO" },
  "802": { city: "Denver", state: "CO" },
  "850": { city: "Phoenix", state: "AZ" },
  "852": { city: "Phoenix", state: "AZ" },
  "900": { city: "Los Angeles", state: "CA" },
  "901": { city: "Los Angeles", state: "CA" },
  "902": { city: "Los Angeles", state: "CA" },
  "919": { city: "San Diego", state: "CA" },
  "921": { city: "San Diego", state: "CA" },
  "941": { city: "San Francisco", state: "CA" },
  "942": { city: "Sacramento", state: "CA" },
  "946": { city: "Oakland", state: "CA" },
  "980": { city: "Seattle", state: "WA" },
  "981": { city: "Seattle", state: "WA" },
  "971": { city: "Portland", state: "OR" },
  "972": { city: "Portland", state: "OR" },
  "890": { city: "Las Vegas", state: "NV" },
  "891": { city: "Las Vegas", state: "NV" },
  "841": { city: "Salt Lake City", state: "UT" },
  "842": { city: "Salt Lake City", state: "UT" },
  "372": { city: "Nashville", state: "TN" },
  "380": { city: "Memphis", state: "TN" },
  "282": { city: "Charlotte", state: "NC" },
  "275": { city: "Raleigh", state: "NC" },
  "681": { city: "Omaha", state: "NE" },
  "531": { city: "Milwaukee", state: "WI" },
  "064": { city: "Stamford", state: "CT" },
  "068": { city: "Greenwich", state: "CT" },
  "070": { city: "Newark", state: "NJ" },
  "071": { city: "Newark", state: "NJ" },
  "074": { city: "Princeton", state: "NJ" },
  "077": { city: "Jersey City", state: "NJ" },
  "200": { city: "Washington", state: "DC" },
  "201": { city: "Washington", state: "DC" },
  "202": { city: "Washington", state: "DC" },
  "203": { city: "Washington", state: "DC" },
  "204": { city: "Washington", state: "DC" },
  "220": { city: "Arlington", state: "VA" },
  "221": { city: "Alexandria", state: "VA" },
  "222": { city: "Arlington", state: "VA" },
  "207": { city: "Bethesda", state: "MD" },
  "208": { city: "Rockville", state: "MD" },
  "212": { city: "Baltimore", state: "MD" },
};

export function lookupZipCode(zip) {
  if (!zip || zip.length < 3) return null;
  const prefix = zip.substring(0, 3);
  return ZIP_PREFIX_DATA[prefix] || null;
}

export function getStatesForCountry(countryCode) {
  return STATES_BY_COUNTRY[countryCode] || [];
}

export function getCitiesForState(stateCode) {
  return CITIES_BY_STATE[stateCode] || [];
}