// Comprehensive states/provinces/regions for all countries (ISO 3166-2).
// Source of truth for the country → state/province drill-down in address forms.
// Countries with no first-level subdivisions are omitted (the address form
// falls back to a free-text State/Province input for those).

export const STATES_BY_COUNTRY = {
  US: [
    { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" }, { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" }, { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" }, { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" }, { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" }, { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" }, { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" },
    { code: "DC", name: "District of Columbia" },
    { code: "PR", name: "Puerto Rico" }, { code: "VI", name: "U.S. Virgin Islands" },
    { code: "GU", name: "Guam" }, { code: "AS", name: "American Samoa" },
    { code: "MP", name: "Northern Mariana Islands" },
  ],
  CA: [
    { code: "AB", name: "Alberta" }, { code: "BC", name: "British Columbia" },
    { code: "MB", name: "Manitoba" }, { code: "NB", name: "New Brunswick" },
    { code: "NL", name: "Newfoundland and Labrador" }, { code: "NS", name: "Nova Scotia" },
    { code: "NT", name: "Northwest Territories" }, { code: "NU", name: "Nunavut" },
    { code: "ON", name: "Ontario" }, { code: "PE", name: "Prince Edward Island" },
    { code: "QC", name: "Quebec" }, { code: "SK", name: "Saskatchewan" },
    { code: "YT", name: "Yukon" },
  ],
  GB: [
    { code: "ENG", name: "England" }, { code: "SCT", name: "Scotland" },
    { code: "WLS", name: "Wales" }, { code: "NIR", name: "Northern Ireland" },
  ],
  AU: [
    { code: "ACT", name: "Australian Capital Territory" },
    { code: "NSW", name: "New South Wales" },
    { code: "NT", name: "Northern Territory" },
    { code: "QLD", name: "Queensland" },
    { code: "SA", name: "South Australia" },
    { code: "TAS", name: "Tasmania" },
    { code: "VIC", name: "Victoria" },
    { code: "WA", name: "Western Australia" },
  ],
  DE: [
    { code: "BW", name: "Baden-Württemberg" }, { code: "BY", name: "Bavaria" },
    { code: "BE", name: "Berlin" }, { code: "BB", name: "Brandenburg" },
    { code: "HB", name: "Bremen" }, { code: "HH", name: "Hamburg" },
    { code: "HE", name: "Hesse" }, { code: "MV", name: "Mecklenburg-Vorpommern" },
    { code: "NI", name: "Lower Saxony" }, { code: "NW", name: "North Rhine-Westphalia" },
    { code: "RP", name: "Rhineland-Palatinate" }, { code: "SL", name: "Saarland" },
    { code: "SN", name: "Saxony" }, { code: "ST", name: "Saxony-Anhalt" },
    { code: "SH", name: "Schleswig-Holstein" }, { code: "TH", name: "Thuringia" },
  ],
  FR: [
    { code: "ARA", name: "Auvergne-Rhône-Alpes" }, { code: "BFC", name: "Bourgogne-Franche-Comté" },
    { code: "BRE", name: "Brittany" }, { code: "CVL", name: "Centre-Val de Loire" },
    { code: "COR", name: "Corsica" }, { code: "GES", name: "Grand Est" },
    { code: "HDF", name: "Hauts-de-France" }, { code: "IDF", name: "Île-de-France" },
    { code: "NOR", name: "Normandy" }, { code: "NAQ", name: "Nouvelle-Aquitaine" },
    { code: "OCC", name: "Occitanie" }, { code: "PDL", name: "Pays de la Loire" },
    { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
  ],
  IT: [
    { code: "65", name: "Abruzzo" }, { code: "77", name: "Basilicata" },
    { code: "78", name: "Calabria" }, { code: "72", name: "Campania" },
    { code: "45", name: "Emilia-Romagna" }, { code: "36", name: "Friuli-Venezia Giulia" },
    { code: "62", name: "Lazio" }, { code: "42", name: "Liguria" },
    { code: "25", name: "Lombardy" }, { code: "57", name: "Marche" },
    { code: "67", name: "Molise" }, { code: "21", name: "Piedmont" },
    { code: "75", name: "Apulia" }, { code: "88", name: "Sardinia" },
    { code: "82", name: "Sicily" }, { code: "52", name: "Tuscany" },
    { code: "55", name: "Umbria" }, { code: "23", name: "Aosta Valley" },
    { code: "34", name: "Veneto" }, { code: "32", name: "Trentino-South Tyrol" },
  ],
  ES: [
    { code: "AN", name: "Andalusia" }, { code: "AR", name: "Aragón" },
    { code: "AS", name: "Asturias" }, { code: "CB", name: "Cantabria" },
    { code: "CM", name: "Castilla-La Mancha" }, { code: "CL", name: "Castile and León" },
    { code: "CT", name: "Catalonia" }, { code: "EX", name: "Extremadura" },
    { code: "GA", name: "Galicia" }, { code: "IB", name: "Balearic Islands" },
    { code: "CN", name: "Canary Islands" }, { code: "RI", name: "La Rioja" },
    { code: "MD", name: "Madrid" }, { code: "MC", name: "Murcia" },
    { code: "NC", name: "Navarre" }, { code: "PV", name: "Basque Country" },
    { code: "VC", name: "Valencian Community" }, { code: "CE", name: "Ceuta" },
    { code: "ML", name: "Melilla" },
  ],
  NL: [
    { code: "DR", name: "Drenthe" }, { code: "FL", name: "Flevoland" },
    { code: "FR", name: "Friesland" }, { code: "GE", name: "Gelderland" },
    { code: "GR", name: "Groningen" }, { code: "LI", name: "Limburg" },
    { code: "NB", name: "North Brabant" }, { code: "NH", name: "North Holland" },
    { code: "OV", name: "Overijssel" }, { code: "UT", name: "Utrecht" },
    { code: "ZE", name: "Zeeland" }, { code: "ZH", name: "South Holland" },
  ],
  BE: [
    { code: "BRU", name: "Brussels-Capital Region" },
    { code: "VLG", name: "Flemish Region" },
    { code: "WAL", name: "Walloon Region" },
  ],
  CH: [
    { code: "AG", name: "Aargau" }, { code: "AR", name: "Appenzell Ausserrhoden" },
    { code: "AI", name: "Appenzell Innerrhoden" }, { code: "BL", name: "Basel-Landschaft" },
    { code: "BS", name: "Basel-Stadt" }, { code: "BE", name: "Bern" },
    { code: "FR", name: "Fribourg" }, { code: "GE", name: "Geneva" },
    { code: "GL", name: "Glarus" }, { code: "GR", name: "Graubünden" },
    { code: "JU", name: "Jura" }, { code: "LU", name: "Lucerne" },
    { code: "NE", name: "Neuchâtel" }, { code: "NW", name: "Nidwalden" },
    { code: "OW", name: "Obwalden" }, { code: "SG", name: "St. Gallen" },
    { code: "SH", name: "Schaffhausen" }, { code: "SZ", name: "Schwyz" },
    { code: "SO", name: "Solothurn" }, { code: "TG", name: "Thurgau" },
    { code: "TI", name: "Ticino" }, { code: "UR", name: "Uri" },
    { code: "VS", name: "Valais" }, { code: "VD", name: "Vaud" },
    { code: "ZG", name: "Zug" }, { code: "ZH", name: "Zürich" },
  ],
  AT: [
    { code: "1", name: "Burgenland" }, { code: "2", name: "Carinthia" },
    { code: "3", name: "Lower Austria" }, { code: "4", name: "Upper Austria" },
    { code: "5", name: "Salzburg" }, { code: "6", name: "Styria" },
    { code: "7", name: "Tyrol" }, { code: "8", name: "Vorarlberg" },
    { code: "9", name: "Vienna" },
  ],
  SE: [
    { code: "K", name: "Blekinge" }, { code: "W", name: "Dalarna" },
    { code: "I", name: "Gotland" }, { code: "X", name: "Gävleborg" },
    { code: "N", name: "Halland" }, { code: "Z", name: "Jämtland" },
    { code: "F", name: "Jönköping" }, { code: "H", name: "Kalmar" },
    { code: "G", name: "Kronoberg" }, { code: "BD", name: "Norrbotten" },
    { code: "M", name: "Skåne" }, { code: "AB", name: "Stockholm" },
    { code: "D", name: "Södermanland" }, { code: "C", name: "Uppsala" },
    { code: "S", name: "Värmland" }, { code: "AC", name: "Västerbotten" },
    { code: "Y", name: "Västernorrland" }, { code: "U", name: "Västmanland" },
    { code: "O", name: "Västra Götaland" }, { code: "T", name: "Örebro" },
    { code: "E", name: "Östergötland" },
  ],
  NO: [
    { code: "03", name: "Oslo" }, { code: "11", name: "Rogaland" },
    { code: "15", name: "Møre og Romsdal" }, { code: "18", name: "Nordland" },
    { code: "30", name: "Viken" }, { code: "34", name: "Innlandet" },
    { code: "38", name: "Vestfold og Telemark" }, { code: "42", name: "Agder" },
    { code: "46", name: "Vestland" }, { code: "50", name: "Trøndelag" },
    { code: "54", name: "Troms og Finnmark" },
  ],
  DK: [
    { code: "81", name: "North Jutland" }, { code: "82", name: "Central Jutland" },
    { code: "83", name: "Southern Denmark" }, { code: "84", name: "Capital Region" },
    { code: "85", name: "Zealand" },
  ],
  FI: [
    { code: "01", name: "Åland" }, { code: "02", name: "South Karelia" },
    { code: "03", name: "South Ostrobothnia" }, { code: "04", name: "South Savo" },
    { code: "05", name: "Kainuu" }, { code: "06", name: "Kanta-Häme" },
    { code: "07", name: "Central Ostrobothnia" }, { code: "08", name: "Central Finland" },
    { code: "09", name: "Kymenlaakso" }, { code: "10", name: "Lapland" },
    { code: "11", name: "Pirkanmaa" }, { code: "12", name: "Ostrobothnia" },
    { code: "13", name: "North Karelia" }, { code: "14", name: "North Ostrobothnia" },
    { code: "15", name: "North Savo" }, { code: "16", name: "Päijät-Häme" },
    { code: "17", name: "Satakunta" }, { code: "18", name: "Uusimaa" },
    { code: "19", name: "Southwest Finland" },
  ],
  IE: [
    { code: "C", name: "Connacht" }, { code: "L", name: "Leinster" },
    { code: "M", name: "Munster" }, { code: "U", name: "Ulster" },
  ],
  PT: [
    { code: "01", name: "Aveiro" }, { code: "02", name: "Beja" },
    { code: "03", name: "Braga" }, { code: "04", name: "Bragança" },
    { code: "05", name: "Castelo Branco" }, { code: "06", name: "Coimbra" },
    { code: "07", name: "Évora" }, { code: "08", name: "Faro" },
    { code: "09", name: "Guarda" }, { code: "10", name: "Leiria" },
    { code: "11", name: "Lisbon" }, { code: "12", name: "Portalegre" },
    { code: "13", name: "Porto" }, { code: "14", name: "Santarém" },
    { code: "15", name: "Setúbal" }, { code: "16", name: "Viana do Castelo" },
    { code: "17", name: "Vila Real" }, { code: "18", name: "Viseu" },
    { code: "20", name: "Azores" }, { code: "30", name: "Madeira" },
  ],
  GR: [
    { code: "I", name: "Attica" }, { code: "A", name: "East Macedonia and Thrace" },
    { code: "C", name: "Central Macedonia" }, { code: "B", name: "West Macedonia" },
    { code: "D", name: "Epirus" }, { code: "E", name: "Thessaly" },
    { code: "F", name: "Ionian Islands" }, { code: "G", name: "West Greece" },
    { code: "H", name: "Central Greece" }, { code: "J", name: "Peloponnese" },
    { code: "K", name: "North Aegean" }, { code: "L", name: "South Aegean" },
    { code: "M", name: "Crete" }, { code: "69", name: "Mount Athos" },
  ],
  PL: [
    { code: "DS", name: "Lower Silesian" }, { code: "KP", name: "Kuyavian-Pomeranian" },
    { code: "LU", name: "Lublin" }, { code: "LB", name: "Lubusz" },
    { code: "LD", name: "Łódź" }, { code: "MA", name: "Lesser Poland" },
    { code: "MZ", name: "Masovian" }, { code: "OP", name: "Opole" },
    { code: "PK", name: "Subcarpathian" }, { code: "PD", name: "Podlaskie" },
    { code: "PM", name: "Pomeranian" }, { code: "SL", name: "Silesian" },
    { code: "SK", name: "Świętokrzyskie" }, { code: "WN", name: "Warmian-Masurian" },
    { code: "WP", name: "Greater Poland" }, { code: "ZP", name: "West Pomeranian" },
  ],
  CZ: [
    { code: "PR", name: "Prague" }, { code: "JC", name: "Central Bohemia" },
    { code: "ST", name: "South Bohemia" }, { code: "PL", name: "Plzeň" },
    { code: "KV", name: "Karlovy Vary" }, { code: "US", name: "Ústí nad Labem" },
    { code: "LI", name: "Liberec" }, { code: "PA", name: "Hradec Králové" },
    { code: "PA", name: "Pardubice" }, { code: "VY", name: "Vysočina" },
    { code: "JM", name: "South Moravia" }, { code: "OL", name: "Olomouc" },
    { code: "ZL", name: "Zlín" }, { code: "MO", name: "Moravia-Silesia" },
  ],
  SK: [
    { code: "BC", name: "Banská Bystrica" }, { code: "BL", name: "Bratislava" },
    { code: "KI", name: "Košice" }, { code: "NI", name: "Nitra" },
    { code: "PV", name: "Prešov" }, { code: "TC", name: "Trenčín" },
    { code: "TA", name: "Trnava" }, { code: "ZI", name: "Žilina" },
  ],
  HU: [
    { code: "BA", name: "Baranya" }, { code: "BK", name: "Bács-Kiskun" },
    { code: "BE", name: "Békés" }, { code: "BZ", name: "Borsod-Abaúj-Zemplén" },
    { code: "CS", name: "Csongrád-Csanád" }, { code: "FE", name: "Fejér" },
    { code: "GS", name: "Győr-Moson-Sopron" }, { code: "HB", name: "Hajdú-Bihar" },
    { code: "HE", name: "Heves" }, { code: "JN", name: "Jász-Nagykun-Szolnok" },
    { code: "KE", name: "Komárom-Esztergom" }, { code: "NO", name: "Nógrád" },
    { code: "PE", name: "Pest" }, { code: "SO", name: "Somogy" },
    { code: "SZ", name: "Szabolcs-Szatmár-Bereg" }, { code: "TO", name: "Tolna" },
    { code: "VA", name: "Vas" }, { code: "VE", name: "Veszprém" },
    { code: "ZA", name: "Zala" }, { code: "BU", name: "Budapest" },
  ],
  RO: [
    { code: "AB", name: "Alba" }, { code: "AR", name: "Arad" },
    { code: "AG", name: "Argeș" }, { code: "BC", name: "Bacău" },
    { code: "BH", name: "Bihor" }, { code: "BN", name: "Bistrița-Năsăud" },
    { code: "BT", name: "Botoșani" }, { code: "BR", name: "Brăila" },
    { code: "BV", name: "Brașov" }, { code: "B", name: "Bucharest" },
    { code: "BZ", name: "Buzău" }, { code: "CS", name: "Caraș-Severin" },
    { code: "CL", name: "Călărași" }, { code: "CJ", name: "Cluj" },
    { code: "CT", name: "Constanța" }, { code: "CV", name: "Covasna" },
    { code: "DB", name: "Dâmbovița" }, { code: "DJ", name: "Dolj" },
    { code: "GL", name: "Galați" }, { code: "GR", name: "Giurgiu" },
    { code: "GJ", name: "Gorj" }, { code: "HR", name: "Harghita" },
    { code: "HD", name: "Hunedoara" }, { code: "IL", name: "Ialomița" },
    { code: "IS", name: "Iași" }, { code: "IF", name: "Ilfov" },
    { code: "MM", name: "Maramureș" }, { code: "MH", name: "Mehedinți" },
    { code: "MS", name: "Mureș" }, { code: "NT", name: "Neamț" },
    { code: "OT", name: "Olt" }, { code: "PH", name: "Prahova" },
    { code: "SJ", name: "Sălaj" }, { code: "SM", name: "Satu Mare" },
    { code: "SB", name: "Sibiu" }, { code: "SV", name: "Suceava" },
    { code: "TR", name: "Teleorman" }, { code: "TM", name: "Timiș" },
    { code: "TL", name: "Tulcea" }, { code: "VS", name: "Vaslui" },
    { code: "VL", name: "Vâlcea" }, { code: "VN", name: "Vrancea" },
  ],
  BG: [
    { code: "01", name: "Blagoevgrad" }, { code: "02", name: "Burgas" },
    { code: "03", name: "Dobrich" }, { code: "04", name: "Gabrovo" },
    { code: "05", name: "Haskovo" }, { code: "06", name: "Kardzhali" },
    { code: "07", name: "Kyustendil" }, { code: "08", name: "Lovech" },
    { code: "09", name: "Montana" }, { code: "10", name: "Pazardzhik" },
    { code: "11", name: "Pernik" }, { code: "12", name: "Pleven" },
    { code: "13", name: "Plovdiv" }, { code: "14", name: "Razgrad" },
    { code: "15", name: "Ruse" }, { code: "16", name: "Shumen" },
    { code: "17", name: "Silistra" }, { code: "18", name: "Sliven" },
    { code: "19", name: "Smolyan" }, { code: "20", name: "Sofia City" },
    { code: "21", name: "Sofia Province" }, { code: "22", name: "Stara Zagora" },
    { code: "23", name: "Targovishte" }, { code: "24", name: "Haskovo" },
    { code: "25", name: "Veliko Tarnovo" }, { code: "26", name: "Vidin" },
    { code: "27", name: "Vratsa" }, { code: "28", name: "Yambol" },
  ],
  HR: [
    { code: "01", name: "Zagreb County" }, { code: "02", name: "Krapina-Zagorje" },
    { code: "03", name: "Sisak-Moslavina" }, { code: "04", name: "Karlovac" },
    { code: "05", name: "Varazdin" }, { code: "06", name: "Koprivnica-Krizevci" },
    { code: "07", name: "Bjelovar-Bilogora" }, { code: "08", name: "Primorje-Gorski Kotar" },
    { code: "09", name: "Lika-Senj" }, { code: "10", name: "Virovka-Podravina" },
    { code: "11", name: "Požega-Slavonia" }, { code: "12", name: "Brod-Posavina" },
    { code: "13", name: "Zadar" }, { code: "14", name: "Osijek-Baranja" },
    { code: "15", name: "Šibenik-Knin" }, { code: "16", name: "Vukovar-Syrmia" },
    { code: "17", name: "Split-Dalmatia" }, { code: "18", name: "Istria" },
    { code: "19", name: "Dubrovnik-Neretva" }, { code: "20", name: "Međimurje" },
    { code: "21", name: "Zagreb City" },
  ],
  SI: [
    { code: "001", name: "Ajdovščina" }, { code: "002", name: "Ankaran" },
    { code: "003", name: "Apače" }, { code: "004", name: "Beltinci" },
    { code: "005", name: "Benedikt" }, { code: "006", name: "Bistrica ob Sotli" },
    { code: "007", name: "Bled" }, { code: "008", name: "Bloke" },
    { code: "009", name: "Bohinj" }, { code: "010", name: "Borovnica" },
    { code: "011", name: "Bovec" }, { code: "012", name: "Braslovče" },
    { code: "013", name: "Brda" }, { code: "014", name: "Brezovica" },
    { code: "015", name: "Brezice" },
  ],
  EE: [
    { code: "37", name: "Harju" }, { code: "39", name: "Hiiu" },
    { code: "44", name: "Ida-Viru" }, { code: "49", name: "Jõgeva" },
    { code: "51", name: "Järva" }, { code: "57", name: "Lääne" },
    { code: "59", name: "Lääne-Viru" }, { code: "65", name: "Põlva" },
    { code: "67", name: "Pärnu" }, { code: "70", name: "Rapla" },
    { code: "74", name: "Saare" }, { code: "78", name: "Tartu" },
    { code: "82", name: "Valga" }, { code: "84", name: "Viljandi" },
    { code: "86", name: "Võru" },
  ],
  LV: [
    { code: "001", name: "Aglona" }, { code: "002", name: "Aizkraukle" },
    { code: "003", name: "Aizpute" }, { code: "004", name: "Aloja" },
    { code: "005", name: "Alsunga" }, { code: "006", name: "Alūksne" },
    { code: "007", name: "Amata" }, { code: "008", name: "Ape" },
    { code: "009", name: "Auce" }, { code: "010", name: "Babīte" },
    { code: "011", name: "Baldone" }, { code: "012", name: "Baltinava" },
    { code: "013", name: "Balvi" }, { code: "014", name: "Bauska" },
    { code: "015", name: "Beverīna" }, { code: "016", name: "Brocenī" },
    { code: "017", name: "Burtnieki" }, { code: "018", name: "Carnikava" },
    { code: "019", name: "Cesvaine" }, { code: "020", name: "Cibla" },
  ],
  LT: [
    { code: "01", name: "Akmenė" }, { code: "02", name: "Alytus City" },
    { code: "03", name: "Alytus District" }, { code: "04", name: "Anykščiai" },
    { code: "05", name: "Birštonas" }, { code: "06", name: "Biržai" },
    { code: "07", name: "Druskininkai" }, { code: "08", name: "Elektrėnai" },
    { code: "09", name: "Ignalina" }, { code: "10", name: "Jonava" },
    { code: "11", name: "Joniškis" }, { code: "12", name: "Jurbarkas" },
    { code: "13", name: "Kaišiadorys" }, { code: "14", name: "Kalvarija" },
    { code: "15", name: "Kaunas City" }, { code: "16", name: "Kaunas District" },
    { code: "17", name: "Kazlų Rūda" }, { code: "18", name: "Kėdainiai" },
    { code: "19", name: "Kelmė" }, { code: "20", name: "Klaipėda City" },
  ],
  LU: [
    { code: "CA", name: "Capellen" }, { code: "CL", name: "Clervaux" },
    { code: "DI", name: "Diekirch" }, { code: "EC", name: "Echternach" },
    { code: "ES", name: "Esch-sur-Alzette" }, { code: "GR", name: "Grevenmacher" },
    { code: "LU", name: "Luxembourg" }, { code: "ME", name: "Mersch" },
    { code: "RD", name: "Redange" }, { code: "RM", name: "Remich" },
    { code: "VD", name: "Vianden" }, { code: "WI", name: "Wiltz" },
  ],
  IS: [
    { code: "1", name: "Capital Region" }, { code: "2", name: "Southern Peninsula" },
    { code: "3", name: "Western Region" }, { code: "4", name: "Westfjords" },
    { code: "5", name: "Northwestern Region" }, { code: "6", name: "Northeastern Region" },
    { code: "7", name: "Eastern Region" }, { code: "8", name: "Southern Region" },
  ],
  MT: [
    { code: "01", name: "Attard" }, { code: "02", name: "Balzan" },
    { code: "03", name: "Birgu" }, { code: "04", name: "Birkirkara" },
    { code: "05", name: "Birżebbuġa" }, { code: "06", name: "Dingli" },
    { code: "07", name: "Fgura" }, { code: "08", name: "Fleur-de-Lys" },
    { code: "09", name: "Floriana" }, { code: "10", name: "Fontana" },
    { code: "11", name: "Gudja" }, { code: "12", name: "Gżira" },
    { code: "13", name: "Għajnsielem" }, { code: "14", name: "Għarb" },
    { code: "15", name: "Għargħur" }, { code: "16", name: "Għasri" },
    { code: "17", name: "Għaxaq" }, { code: "18", name: "Ħamrun" },
  ],
  CY: [
    { code: "01", name: "Nicosia" }, { code: "02", name: "Limassol" },
    { code: "03", name: "Larnaca" }, { code: "04", name: "Famagusta" },
    { code: "05", name: "Paphos" }, { code: "06", name: "Kyrenia" },
  ],
  RU: [
    { code: "MOW", name: "Moscow" }, { code: "SPE", name: "Saint Petersburg" },
    { code: "AD", name: "Adygea" }, { code: "AL", name: "Altai Republic" },
    { code: "ALT", name: "Altai Krai" }, { code: "AMU", name: "Amur Oblast" },
    { code: "ARK", name: "Arkhangelsk Oblast" }, { code: "AST", name: "Astrakhan Oblast" },
    { code: "BA", name: "Bashkortostan" }, { code: "BEL", name: "Belgorod Oblast" },
    { code: "BRY", name: "Bryansk Oblast" }, { code: "BU", name: "Buryatia" },
    { code: "CE", name: "Chechnya" }, { code: "CHE", name: "Chelyabinsk Oblast" },
    { code: "CU", name: "Chuvashia" }, { code: "DA", name: "Dagestan" },
    { code: "IRK", name: "Irkutsk Oblast" }, { code: "IVA", name: "Ivanovo Oblast" },
    { code: "KDA", name: "Krasnodar Krai" }, { code: "KEM", name: "Kemerovo Oblast" },
    { code: "KGD", name: "Kaliningrad Oblast" }, { code: "KGN", name: "Kurgan Oblast" },
    { code: "KHA", name: "Khabarovsk Krai" }, { code: "KHM", name: "Khanty-Mansi" },
    { code: "KIR", name: "Kirov Oblast" }, { code: "KK", name: "Khakassia" },
    { code: "KL", name: "Kalmykia" }, { code: "KLU", name: "Kaluga Oblast" },
    { code: "KOS", name: "Kostroma Oblast" }, { code: "KR", name: "Karelia" },
    { code: "KRS", name: "Kursk Oblast" }, { code: "LEN", name: "Leningrad Oblast" },
    { code: "LIP", name: "Lipetsk Oblast" }, { code: "MAG", name: "Magadan Oblast" },
    { code: "ME", name: "Mari El" }, { code: "MO", name: "Mordovia" },
    { code: "MOS", name: "Moscow Oblast" }, { code: "MUR", name: "Murmansk Oblast" },
    { code: "NIZ", name: "Nizhny Novgorod Oblast" }, { code: "NGR", name: "Novgorod Oblast" },
    { code: "NVS", name: "Novosibirsk Oblast" }, { code: "OMS", name: "Omsk Oblast" },
    { code: "ORE", name: "Orenburg Oblast" }, { code: "ORL", name: "Oryol Oblast" },
    { code: "PNZ", name: "Penza Oblast" }, { code: "PER", name: "Perm Krai" },
    { code: "PRI", name: "Primorsky Krai" }, { code: "PSK", name: "Pskov Oblast" },
    { code: "ROS", name: "Rostov Oblast" }, { code: "RYA", name: "Ryazan Oblast" },
    { code: "SAM", name: "Samara Oblast" }, { code: "SAR", name: "Saratov Oblast" },
    { code: "SAK", name: "Sakhalin Oblast" }, { code: "SVE", name: "Sverdlovsk Oblast" },
    { code: "SMO", name: "Smolensk Oblast" }, { code: "TAM", name: "Tambov Oblast" },
    { code: "TAT", name: "Tatarstan" }, { code: "TOM", name: "Tomsk Oblast" },
    { code: "TUL", name: "Tula Oblast" }, { code: "TVE", name: "Tver Oblast" },
    { code: "TYU", name: "Tyumen Oblast" }, { code: "UD", name: "Udmurtia" },
    { code: "ULY", name: "Ulyanovsk Oblast" }, { code: "VGG", name: "Volgograd Oblast" },
    { code: "VLG", name: "Vologda Oblast" }, { code: "VOR", name: "Voronezh Oblast" },
    { code: "YAR", name: "Yaroslavl Oblast" }, { code: "YEV", name: "Yevrey" },
  ],
  UA: [
    { code: "05", name: "Vinnytsia" }, { code: "07", name: "Volyn" },
    { code: "09", name: "Luhansk" }, { code: "12", name: "Dnipropetrovsk" },
    { code: "14", name: "Donetsk" }, { code: "18", name: "Zhytomyr" },
    { code: "21", name: "Zakarpattia" }, { code: "23", name: "Zaporizhzhia" },
    { code: "26", name: "Ivano-Frankivsk" }, { code: "30", name: "Kyiv City" },
    { code: "32", name: "Kyiv" }, { code: "35", name: "Kirovohrad" },
    { code: "40", name: "Lviv" }, { code: "43", name: "Mykolaiv" },
    { code: "46", name: "Odesa" }, { code: "48", name: "Poltava" },
    { code: "51", name: "Rivne" }, { code: "53", name: "Sumy" },
    { code: "56", name: "Ternopil" }, { code: "59", name: "Kharkiv" },
    { code: "61", name: "Kherson" }, { code: "63", name: "Khmelnytskyi" },
    { code: "65", name: "Cherkasy" }, { code: "68", name: "Chernihiv" },
    { code: "71", name: "Chernivtsi" }, { code: "74", name: "Crimea" },
    { code: "77", name: "Sevastopol" },
  ],
  TR: [
    { code: "01", name: "Adana" }, { code: "02", name: "Adıyaman" },
    { code: "03", name: "Afyonkarahisar" }, { code: "04", name: "Ağrı" },
    { code: "05", name: "Amasya" }, { code: "06", name: "Ankara" },
    { code: "07", name: "Antalya" }, { code: "08", name: "Artvin" },
    { code: "09", name: "Aydın" }, { code: "10", name: "Balıkesir" },
    { code: "11", name: "Bilecik" }, { code: "12", name: "Bingöl" },
    { code: "13", name: "Bitlis" }, { code: "14", name: "Bolu" },
    { code: "15", name: "Burdur" }, { code: "16", name: "Bursa" },
    { code: "17", name: "Çanakkale" }, { code: "18", name: "Çankırı" },
    { code: "19", name: "Çorum" }, { code: "20", name: "Denizli" },
    { code: "21", name: "Diyarbakır" }, { code: "22", name: "Edirne" },
    { code: "23", name: "Elazığ" }, { code: "24", name: "Erzincan" },
    { code: "25", name: "Erzurum" }, { code: "26", name: "Eskişehir" },
    { code: "27", name: "Gaziantep" }, { code: "28", name: "Giresun" },
    { code: "29", name: "Gümüşhane" }, { code: "30", name: "Hakkari" },
    { code: "31", name: "Hatay" }, { code: "32", name: "Isparta" },
    { code: "33", name: "Mersin" }, { code: "34", name: "Istanbul" },
    { code: "35", name: "İzmir" }, { code: "36", name: "Kars" },
    { code: "37", name: "Kastamonu" }, { code: "38", name: "Kayseri" },
    { code: "39", name: "Kırklareli" }, { code: "40", name: "Kırşehir" },
    { code: "41", name: "Kocaeli" }, { code: "42", name: "Konya" },
    { code: "43", name: "Kütahya" }, { code: "44", name: "Malatya" },
    { code: "45", name: "Manisa" }, { code: "46", name: "Kahramanmaraş" },
    { code: "47", name: "Mardin" }, { code: "48", name: "Muğla" },
    { code: "49", name: "Muş" }, { code: "50", name: "Nevşehir" },
    { code: "51", name: "Niğde" }, { code: "52", name: "Ordu" },
    { code: "53", name: "Rize" }, { code: "54", name: "Sakarya" },
    { code: "55", name: "Samsun" }, { code: "56", name: "Siirt" },
    { code: "57", name: "Sinop" }, { code: "58", name: "Sivas" },
    { code: "59", name: "Tekirdağ" }, { code: "60", name: "Tokat" },
    { code: "61", name: "Trabzon" }, { code: "62", name: "Tunceli" },
    { code: "63", name: "Şanlıurfa" }, { code: "64", name: "Uşak" },
    { code: "65", name: "Van" }, { code: "66", name: "Yozgat" },
    { code: "67", name: "Zonguldak" }, { code: "68", name: "Aksaray" },
    { code: "69", name: "Bayburt" }, { code: "70", name: "Karaman" },
    { code: "71", name: "Kırıkkale" }, { code: "72", name: "Batman" },
    { code: "73", name: "Şırnak" }, { code: "74", name: "Bartın" },
    { code: "75", name: "Ardahan" }, { code: "76", name: "Iğdır" },
    { code: "77", name: "Yalova" }, { code: "78", name: "Karabük" },
    { code: "79", name: "Kilis" }, { code: "80", name: "Osmaniye" },
    { code: "81", name: "Düzce" },
  ],
  IL: [
    { code: "D", name: "Southern District" }, { code: "M", name: "Central District" },
    { code: "TA", name: "Tel Aviv District" }, { code: "HA", name: "Haifa District" },
    { code: "Z", name: "Northern District" }, { code: "JM", name: "Jerusalem District" },
  ],
  AE: [
    { code: "AZ", name: "Abu Dhabi" }, { code: "AJ", name: "Ajman" },
    { code: "FU", name: "Fujairah" }, { code: "SH", name: "Sharjah" },
    { code: "DXB", name: "Dubai" }, { code: "RK", name: "Ras al-Khaimah" },
    { code: "UQ", name: "Umm al-Quwain" },
  ],
  SA: [
    { code: "01", name: "Riyadh" }, { code: "02", name: "Makkah" },
    { code: "03", name: "Madinah" }, { code: "05", name: "Qassim" },
    { code: "06", name: "Eastern Province" }, { code: "07", name: "Asir" },
    { code: "08", name: "Tabuk" }, { code: "09", name: "Hail" },
    { code: "10", name: "Northern Borders" }, { code: "11", name: "Jizan" },
    { code: "12", name: "Najran" }, { code: "14", name: "Al Bahah" },
    { code: "13", name: "Al Jouf" },
  ],
  QA: [
    { code: "DA", name: "Doha" }, { code: "AL", name: "Al Rayyan" },
    { code: "WA", name: "Al Wakrah" }, { code: "KH", name: "Al Khor" },
    { code: "ZA", name: "Al Shamal" }, { code: "MS", name: "Mesairie" },
    { code: "US", name: "Umm Salal" },
  ],
  KW: [
    { code: "AH", name: "Al Ahmadi" }, { code: "FA", name: "Al Farwaniyah" },
    { code: "HA", name: "Hawalli" }, { code: "JA", name: "Jahra" },
    { code: "KU", name: "Kuwait City" }, { code: "MU", name: "Mubarak Al-Kabeer" },
  ],
  BH: [
    { code: "13", name: "Capital Governorate" }, { code: "14", name: "Muharraq" },
    { code: "15", name: "Northern Governorate" }, { code: "16", name: "Southern Governorate" },
  ],
  OM: [
    { code: "BA", name: "Al Batinah North" }, { code: "BS", name: "Al Batinah South" },
    { code: "BR", name: "Al Buraimi" }, { code: "DA", name: "Ad Dakhiliyah" },
    { code: "MA", name: "Muscat" }, { code: "MU", name: "Musandam" },
    { code: "ZU", name: "Al Dhahirah" }, { code: "SH", name: "Ash Sharqiyah North" },
    { code: "SJ", name: "Ash Sharqiyah South" }, { code: "WU", name: "Al Wusta" },
    { code: "ZU", name: "Dhofar" },
  ],
  EG: [
    { code: "C", name: "Cairo" }, { code: "ALX", name: "Alexandria" },
    { code: "GZ", name: "Giza" }, { code: "SHR", name: "Sharqia" },
    { code: "DK", name: "Dakahlia" }, { code: "BH", name: "Beheira" },
    { code: "MT", name: "Matrouh" }, { code: "WAD", name: "New Valley" },
    { code: "IS", name: "Ismailia" }, { code: "SU", name: "Suez" },
    { code: "SIN", name: "North Sinai" }, { code: "JS", name: "South Sinai" },
    { code: "FYM", name: "Faiyum" }, { code: "BNS", name: "Beni Suef" },
    { code: "MNF", name: "Minya" }, { code: "ASW", name: "Aswan" },
    { code: "AST", name: "Asyut" }, { code: "KN", name: "Qena" },
    { code: "LX", name: "Luxor" }, { code: "SFG", name: "Sohag" },
    { code: "PTS", name: "Port Said" }, { code: "DT", name: "Damietta" },
    { code: "KFS", name: "Kafr El Sheikh" }, { code: "GH", name: "Gharbia" },
    { code: "MN", name: "Monufia" }, { code: "QAL", name: "Qalyubia" },
  ],
  ZA: [
    { code: "EC", name: "Eastern Cape" }, { code: "FS", name: "Free State" },
    { code: "GP", name: "Gauteng" }, { code: "KZN", name: "KwaZulu-Natal" },
    { code: "LP", name: "Limpopo" }, { code: "MP", name: "Mpumalanga" },
    { code: "NC", name: "Northern Cape" }, { code: "NW", name: "North West" },
    { code: "WC", name: "Western Cape" },
  ],
  NG: [
    { code: "AB", name: "Abia" }, { code: "FC", name: "Federal Capital Territory" },
    { code: "AD", name: "Adamawa" }, { code: "AK", name: "Akwa Ibom" },
    { code: "AN", name: "Anambra" }, { code: "BA", name: "Bauchi" },
    { code: "BY", name: "Bayelsa" }, { code: "BE", name: "Benue" },
    { code: "BO", name: "Borno" }, { code: "CR", name: "Cross River" },
    { code: "DE", name: "Delta" }, { code: "EB", name: "Ebonyi" },
    { code: "ED", name: "Edo" }, { code: "EK", name: "Ekiti" },
    { code: "EN", name: "Enugu" }, { code: "GO", name: "Gombe" },
    { code: "IM", name: "Imo" }, { code: "JI", name: "Jigawa" },
    { code: "KD", name: "Kaduna" }, { code: "KN", name: "Kano" },
    { code: "KT", name: "Katsina" }, { code: "KE", name: "Kebbi" },
    { code: "KO", name: "Kogi" }, { code: "KW", name: "Kwara" },
    { code: "LA", name: "Lagos" }, { code: "NA", name: "Nasarawa" },
    { code: "NI", name: "Niger" }, { code: "OG", name: "Ogun" },
    { code: "ON", name: "Ondo" }, { code: "OS", name: "Osun" },
    { code: "OY", name: "Oyo" }, { code: "PL", name: "Plateau" },
    { code: "RI", name: "Rivers" }, { code: "SO", name: "Sokoto" },
    { code: "TA", name: "Taraba" }, { code: "YO", name: "Yobe" },
    { code: "ZA", name: "Zamfara" },
  ],
  KE: [
    { code: "01", name: "Baringo" }, { code: "02", name: "Bomet" },
    { code: "03", name: "Bungoma" }, { code: "04", name: "Busia" },
    { code: "05", name: "Embu" }, { code: "06", name: "Garissa" },
    { code: "07", name: "Homa Bay" }, { code: "08", name: "Isiolo" },
    { code: "09", name: "Kajiado" }, { code: "10", name: "Kakamega" },
    { code: "11", name: "Kericho" }, { code: "12", name: "Kiambu" },
    { code: "13", name: "Kilifi" }, { code: "14", name: "Kirinyaga" },
    { code: "15", name: "Kisii" }, { code: "16", name: "Kisumu" },
    { code: "17", name: "Kitui" }, { code: "18", name: "Kwale" },
    { code: "19", name: "Laikipia" }, { code: "20", name: "Lamu" },
    { code: "21", name: "Machakos" }, { code: "22", name: "Makueni" },
    { code: "23", name: "Mandera" }, { code: "24", name: "Marsabit" },
    { code: "25", name: "Meru" }, { code: "26", name: "Migori" },
    { code: "27", name: "Marsabit" }, { code: "28", name: "Mombasa" },
    { code: "29", name: "Murang'a" }, { code: "30", name: "Nairobi" },
    { code: "31", name: "Nakuru" }, { code: "32", name: "Nandi" },
    { code: "33", name: "Narok" }, { code: "34", name: "Nyamira" },
    { code: "35", name: "Nyandarua" }, { code: "36", name: "Nyeri" },
    { code: "37", name: "Samburu" }, { code: "38", name: "Siaya" },
    { code: "39", name: "Taita-Taveta" }, { code: "40", name: "Tana River" },
    { code: "41", name: "Tharaka-Nithi" }, { code: "42", name: "Trans Nzoia" },
    { code: "43", name: "Turkana" }, { code: "44", name: "Uasin Gishu" },
    { code: "45", name: "Vihiga" }, { code: "46", name: "Wajir" },
    { code: "47", name: "West Pokot" },
  ],
  MA: [
    { code: "01", name: "Tanger-Tétouan-Al Hoceïma" }, { code: "02", name: "Oriental" },
    { code: "03", name: "Fès-Meknès" }, { code: "04", name: "Rabat-Salé-Kénitra" },
    { code: "05", name: "Béni Mellal-Khénifra" }, { code: "06", name: "Casablanca-Settat" },
    { code: "07", name: "Marrakech-Safi" }, { code: "08", name: "Drâa-Tafilalet" },
    { code: "09", name: "Souss-Massa" }, { code: "10", name: "Guelmim-Oued Noun" },
    { code: "11", name: "Laâyoune-Sakia El Hamra" }, { code: "12", name: "Dakhla-Oued Ed-Dahab" },
  ],
  BR: [
    { code: "AC", name: "Acre" }, { code: "AL", name: "Alagoas" },
    { code: "AP", name: "Amapá" }, { code: "AM", name: "Amazonas" },
    { code: "BA", name: "Bahia" }, { code: "CE", name: "Ceará" },
    { code: "DF", name: "Federal District" }, { code: "ES", name: "Espírito Santo" },
    { code: "GO", name: "Goiás" }, { code: "MA", name: "Maranhão" },
    { code: "MT", name: "Mato Grosso" }, { code: "MS", name: "Mato Grosso do Sul" },
    { code: "MG", name: "Minas Gerais" }, { code: "PA", name: "Pará" },
    { code: "PB", name: "Paraíba" }, { code: "PR", name: "Paraná" },
    { code: "PE", name: "Pernambuco" }, { code: "PI", name: "Piauí" },
    { code: "RJ", name: "Rio de Janeiro" }, { code: "RN", name: "Rio Grande do Norte" },
    { code: "RS", name: "Rio Grande do Sul" }, { code: "RO", name: "Rondônia" },
    { code: "RR", name: "Roraima" }, { code: "SC", name: "Santa Catarina" },
    { code: "SP", name: "São Paulo" }, { code: "SE", name: "Sergipe" },
    { code: "TO", name: "Tocantins" },
  ],
  AR: [
    { code: "B", name: "Buenos Aires" }, { code: "K", name: "Catamarca" },
    { code: "H", name: "Chaco" }, { code: "U", name: "Chubut" },
    { code: "C", name: "Ciudad de Buenos Aires" }, { code: "X", name: "Córdoba" },
    { code: "W", name: "Corrientes" }, { code: "E", name: "Entre Ríos" },
    { code: "P", name: "Formosa" }, { code: "Y", name: "Jujuy" },
    { code: "L", name: "La Pampa" }, { code: "F", name: "La Rioja" },
    { code: "M", name: "Mendoza" }, { code: "N", name: "Misiones" },
    { code: "Q", name: "Neuquén" }, { code: "R", name: "Río Negro" },
    { code: "A", name: "Salta" }, { code: "J", name: "San Juan" },
    { code: "D", name: "San Luis" }, { code: "Z", name: "Santa Cruz" },
    { code: "S", name: "Santa Fe" }, { code: "G", name: "Santiago del Estero" },
    { code: "V", name: "Tierra del Fuego" }, { code: "T", name: "Tucumán" },
  ],
  CL: [
    { code: "AI", name: "Arica y Parinacota" }, { code: "TA", name: "Tarapacá" },
    { code: "AN", name: "Antofagasta" }, { code: "AT", name: "Atacama" },
    { code: "CO", name: "Coquimbo" }, { code: "VS", name: "Valparaíso" },
    { code: "RM", name: "Santiago Metropolitan" }, { code: "LI", name: "O'Higgins" },
    { code: "ML", name: "Maule" }, { code: "NB", name: "Ñuble" },
    { code: "BI", name: "Biobío" }, { code: "AR", name: "Araucanía" },
    { code: "LR", name: "Los Ríos" }, { code: "LL", name: "Los Lagos" },
    { code: "AI", name: "Aysén" }, { code: "MA", name: "Magallanes" },
  ],
  CO: [
    { code: "05", name: "Antioquia" }, { code: "08", name: "Atlántico" },
    { code: "11", name: "Bogotá D.C." }, { code: "13", name: "Bolívar" },
    { code: "15", name: "Boyacá" }, { code: "17", name: "Caldas" },
    { code: "18", name: "Caquetá" }, { code: "19", name: "Cauca" },
    { code: "20", name: "Cesar" }, { code: "23", name: "Córdoba" },
    { code: "25", name: "Cundinamarca" }, { code: "27", name: "Chocó" },
    { code: "41", name: "Huila" }, { code: "44", name: "La Guajira" },
    { code: "47", name: "Magdalena" }, { code: "50", name: "Meta" },
    { code: "52", name: "Nariño" }, { code: "54", name: "Norte de Santander" },
    { code: "63", name: "Quindío" }, { code: "66", name: "Risaralda" },
    { code: "68", name: "Santander" }, { code: "70", name: "Sucre" },
    { code: "73", name: "Tolima" }, { code: "76", name: "Valle del Cauca" },
    { code: "88", name: "Archipiélago de San Andrés" }, { code: "91", name: "Amazonas" },
    { code: "94", name: "Guainía" }, { code: "95", name: "Guaviare" },
    { code: "97", name: "Vaupés" }, { code: "99", name: "Vichada" },
    { code: "81", name: "Arauca" }, { code: "85", name: "Casanare" },
    { code: "86", name: "Putumayo" },
  ],
  PE: [
    { code: "AMA", name: "Amazonas" }, { code: "ANC", name: "Ancash" },
    { code: "APU", name: "Apurímac" }, { code: "ARE", name: "Arequipa" },
    { code: "AYA", name: "Ayacucho" }, { code: "CAJ", name: "Cajamarca" },
    { code: "CUS", name: "Cusco" }, { code: "HUV", name: "Huancavelica" },
    { code: "HUC", name: "Huánuco" }, { code: "ICA", name: "Ica" },
    { code: "JUN", name: "Junín" }, { code: "LAL", name: "La Libertad" },
    { code: "LAM", name: "Lambayeque" }, { code: "LIM", name: "Lima" },
    { code: "LMA", name: "Lima Province" }, { code: "LOR", name: "Loreto" },
    { code: "MDD", name: "Madre de Dios" }, { code: "MOQ", name: "Moquegua" },
    { code: "PAS", name: "Pasco" }, { code: "PIU", name: "Piura" },
    { code: "PUN", name: "Puno" }, { code: "SAM", name: "San Martín" },
    { code: "TAC", name: "Tacna" }, { code: "TUM", name: "Tumbes" },
    { code: "UCA", name: "Ucayali" },
  ],
  MX: [
    { code: "AGU", name: "Aguascalientes" }, { code: "BCN", name: "Baja California" },
    { code: "BCS", name: "Baja California Sur" }, { code: "CAM", name: "Campeche" },
    { code: "CHP", name: "Chiapas" }, { code: "CHH", name: "Chihuahua" },
    { code: "CMX", name: "Mexico City" }, { code: "COA", name: "Coahuila" },
    { code: "COL", name: "Colima" }, { code: "DUR", name: "Durango" },
    { code: "GUA", name: "Guanajuato" }, { code: "GRO", name: "Guerrero" },
    { code: "HID", name: "Hidalgo" }, { code: "JAL", name: "Jalisco" },
    { code: "MEX", name: "México State" }, { code: "MIC", name: "Michoacán" },
    { code: "MOR", name: "Morelos" }, { code: "NAY", name: "Nayarit" },
    { code: "NLE", name: "Nuevo León" }, { code: "OAX", name: "Oaxaca" },
    { code: "PUE", name: "Puebla" }, { code: "QUE", name: "Querétaro" },
    { code: "ROO", name: "Quintana Roo" }, { code: "SLP", name: "San Luis Potosí" },
    { code: "SIN", name: "Sinaloa" }, { code: "SON", name: "Sonora" },
    { code: "TAB", name: "Tabasco" }, { code: "TAM", name: "Tamaulipas" },
    { code: "TLA", name: "Tlaxcala" }, { code: "VER", name: "Veracruz" },
    { code: "YUC", name: "Yucatán" }, { code: "ZAC", name: "Zacatecas" },
  ],
  VE: [
    { code: "A", name: "Capital District" }, { code: "B", name: "Anzoátegui" },
    { code: "C", name: "Apure" }, { code: "D", name: "Aragua" },
    { code: "E", name: "Barinas" }, { code: "F", name: "Bolívar" },
    { code: "G", name: "Carabobo" }, { code: "H", name: "Cojedes" },
    { code: "I", name: "Falcón" }, { code: "J", name: "Guárico" },
    { code: "K", name: "Lara" }, { code: "L", name: "Mérida" },
    { code: "M", name: "Miranda" }, { code: "N", name: "Monagas" },
    { code: "O", name: "Nueva Esparta" }, { code: "P", name: "Portuguesa" },
    { code: "R", name: "Sucre" }, { code: "S", name: "Táchira" },
    { code: "T", name: "Trujillo" }, { code: "U", name: "Yaracuy" },
    { code: "V", name: "Zulia" }, { code: "W", name: "Federal Dependencies" },
    { code: "X", name: "La Guaira" }, { code: "Y", name: "Delta Amacuro" },
    { code: "Z", name: "Amazonas" },
  ],
  EC: [
    { code: "A", name: "Azuay" }, { code: "B", name: "Bolívar" },
    { code: "C", name: "Carchi" }, { code: "H", name: "Chimborazo" },
    { code: "X", name: "Cotopaxi" }, { code: "O", name: "El Oro" },
    { code: "E", name: "Esmeraldas" }, { code: "W", name: "Galápagos" },
    { code: "G", name: "Guayas" }, { code: "I", name: "Imbabura" },
    { code: "L", name: "Loja" }, { code: "R", name: "Los Ríos" },
    { code: "M", name: "Manabí" }, { code: "S", name: "Morona Santiago" },
    { code: "N", name: "Napo" }, { code: "D", name: "Orellana" },
    { code: "Y", name: "Pastaza" }, { code: "P", name: "Pichincha" },
    { code: "SE", name: "Santa Elena" }, { code: "SD", name: "Santo Domingo" },
    { code: "U", name: "Sucumbíos" }, { code: "T", name: "Tungurahua" },
    { code: "Z", name: "Zamora-Chinchipe" },
  ],
  UY: [
    { code: "AR", name: "Artigas" }, { code: "CA", name: "Canelones" },
    { code: "CL", name: "Cerro Largo" }, { code: "CO", name: "Colonia" },
    { code: "DU", name: "Durazno" }, { code: "FS", name: "Flores" },
    { code: "FD", name: "Florida" }, { code: "LA", name: "Lavalleja" },
    { code: "MA", name: "Maldonado" }, { code: "MO", name: "Montevideo" },
    { code: "PA", name: "Paysandú" }, { code: "RN", name: "Río Negro" },
    { code: "RV", name: "Rivera" }, { code: "RO", name: "Rocha" },
    { code: "SA", name: "Salto" }, { code: "SJ", name: "San José" },
    { code: "SO", name: "Soriano" }, { code: "TA", name: "Tacuarembó" },
    { code: "TT", name: "Treinta y Tres" },
  ],
  PY: [
    { code: "ASU", name: "Asunción" }, { code: "1", name: "Concepción" },
    { code: "2", name: "San Pedro" }, { code: "3", name: "Cordillera" },
    { code: "4", name: "Guairá" }, { code: "5", name: "Caaguazú" },
    { code: "6", name: "Caazapá" }, { code: "7", name: "Itapúa" },
    { code: "8", name: "Misiones" }, { code: "9", name: "Paraguarí" },
    { code: "10", name: "Alto Paraná" }, { code: "11", name: "Central" },
    { code: "12", name: "Ñeembucú" }, { code: "13", name: "Amambay" },
    { code: "14", name: "Canindeyú" }, { code: "15", name: "Presidente Hayes" },
    { code: "16", name: "Alto Paraguay" }, { code: "19", name: "Boquerón" },
  ],
  BO: [
    { code: "B", name: "Beni" }, { code: "C", name: "Cochabamba" },
    { code: "H", name: "Chuquisaca" }, { code: "L", name: "La Paz" },
    { code: "O", name: "Oruro" }, { code: "N", name: "Pando" },
    { code: "P", name: "Potosí" }, { code: "S", name: "Santa Cruz" },
    { code: "T", name: "Tarija" },
  ],
  CR: [
    { code: "A", name: "Alajuela" }, { code: "C", name: "Cartago" },
    { code: "G", name: "Guanacaste" }, { code: "H", name: "Heredia" },
    { code: "L", name: "Limón" }, { code: "P", name: "Puntarenas" },
    { code: "SJ", name: "San José" },
  ],
  PA: [
    { code: "1", name: "Bocas del Toro" }, { code: "2", name: "Coclé" },
    { code: "3", name: "Colón" }, { code: "4", name: "Chiriquí" },
    { code: "5", name: "Darién" }, { code: "6", name: "Herrera" },
    { code: "7", name: "Los Santos" }, { code: "8", name: "Panamá" },
    { code: "9", name: "Veraguas" }, { code: "10", name: "Guna Yala" },
    { code: "EM", name: "Emberá" }, { code: "NB", name: "Ngäbe-Buglé" },
  ],
  GT: [
    { code: "AV", name: "Alta Verapaz" }, { code: "BV", name: "Baja Verapaz" },
    { code: "CM", name: "Chimaltenango" }, { code: "CQ", name: "Chiquimula" },
    { code: "PR", name: "El Progreso" }, { code: "ES", name: "Escuintla" },
    { code: "GU", name: "Guatemala" }, { code: "HU", name: "Huehuetenango" },
    { code: "IZ", name: "Izabal" }, { code: "JA", name: "Jalapa" },
    { code: "JU", name: "Jutiapa" }, { code: "PE", name: "Petén" },
    { code: "QZ", name: "Quetzaltenango" }, { code: "QC", name: "Quiché" },
    { code: "RE", name: "Retalhuleu" }, { code: "SA", name: "Sacatepéquez" },
    { code: "SM", name: "San Marcos" }, { code: "SR", name: "Santa Rosa" },
    { code: "SO", name: "Sololá" }, { code: "SU", name: "Suchitepéquez" },
    { code: "TO", name: "Totonicapán" }, { code: "ZA", name: "Zacapa" },
  ],
  DO: [
    { code: "01", name: "Distrito Nacional" }, { code: "02", name: "Azua" },
    { code: "03", name: "Bahoruco" }, { code: "04", name: "Barahona" },
    { code: "05", name: "Dajabón" }, { code: "06", name: "Duarte" },
    { code: "07", name: "Elías Piña" }, { code: "08", name: "El Seibo" },
    { code: "09", name: "Espaillat" }, { code: "10", name: "Independencia" },
    { code: "11", name: "La Altagracia" }, { code: "12", name: "La Romana" },
    { code: "13", name: "La Vega" }, { code: "14", name: "María Trinidad Sánchez" },
    { code: "15", name: "Monte Cristi" }, { code: "16", name: "Pedernales" },
    { code: "17", name: "Peravia" }, { code: "18", name: "Puerto Plata" },
    { code: "19", name: "Hermanas Mirabal" }, { code: "20", name: "Samaná" },
    { code: "21", name: "San Cristóbal" }, { code: "22", name: "San Juan" },
    { code: "23", name: "San Pedro de Macorís" }, { code: "24", name: "Sánchez Ramírez" },
    { code: "25", name: "Santiago" }, { code: "26", name: "Santiago Rodríguez" },
    { code: "27", name: "Valverde" }, { code: "28", name: "Monseñor Nouel" },
    { code: "29", name: "Monte Plata" }, { code: "30", name: "Hato Mayor" },
  ],
  IN: [
    { code: "AN", name: "Andhra Pradesh" }, { code: "AR", name: "Arunachal Pradesh" },
    { code: "AS", name: "Assam" }, { code: "BR", name: "Bihar" },
    { code: "CG", name: "Chhattisgarh" }, { code: "GA", name: "Goa" },
    { code: "GJ", name: "Gujarat" }, { code: "HR", name: "Haryana" },
    { code: "HP", name: "Himachal Pradesh" }, { code: "JH", name: "Jharkhand" },
    { code: "KA", name: "Karnataka" }, { code: "KL", name: "Kerala" },
    { code: "MP", name: "Madhya Pradesh" }, { code: "MH", name: "Maharashtra" },
    { code: "MN", name: "Manipur" }, { code: "ML", name: "Meghalaya" },
    { code: "MZ", name: "Mizoram" }, { code: "NL", name: "Nagaland" },
    { code: "OR", name: "Odisha" }, { code: "PB", name: "Punjab" },
    { code: "RJ", name: "Rajasthan" }, { code: "SK", name: "Sikkim" },
    { code: "TN", name: "Tamil Nadu" }, { code: "TG", name: "Telangana" },
    { code: "TR", name: "Tripura" }, { code: "UP", name: "Uttar Pradesh" },
    { code: "UT", name: "Uttarakhand" }, { code: "WB", name: "West Bengal" },
    { code: "DL", name: "Delhi" }, { code: "JK", name: "Jammu and Kashmir" },
    { code: "LA", name: "Ladakh" }, { code: "CH", name: "Chandigarh" },
    { code: "PY", name: "Puducherry" }, { code: "AN", name: "Andaman and Nicobar Islands" },
    { code: "DH", name: "Dadra and Nagar Haveli and Daman and Diu" },
    { code: "LD", name: "Lakshadweep" },
  ],
  PK: [
    { code: "PB", name: "Punjab" }, { code: "SD", name: "Sindh" },
    { code: "KP", name: "Khyber Pakhtunkhwa" }, { code: "BA", name: "Balochistan" },
    { code: "GB", name: "Gilgit-Baltistan" }, { code: "JK", name: "Azad Kashmir" },
    { code: "IS", name: "Islamabad Capital Territory" },
  ],
  CN: [
    { code: "AH", name: "Anhui" }, { code: "BJ", name: "Beijing" },
    { code: "CQ", name: "Chongqing" }, { code: "FJ", name: "Fujian" },
    { code: "GS", name: "Gansu" }, { code: "GD", name: "Guangdong" },
    { code: "GX", name: "Guangxi" }, { code: "GZ", name: "Guizhou" },
    { code: "HA", name: "Hainan" }, { code: "HE", name: "Hebei" },
    { code: "HL", name: "Heilongjiang" }, { code: "HN", name: "Henan" },
    { code: "HB", name: "Hubei" }, { code: "HU", name: "Hunan" },
    { code: "JS", name: "Jiangsu" }, { code: "JX", name: "Jiangxi" },
    { code: "JL", name: "Jilin" }, { code: "LN", name: "Liaoning" },
    { code: "NM", name: "Inner Mongolia" }, { code: "NX", name: "Ningxia" },
    { code: "QH", name: "Qinghai" }, { code: "SC", name: "Sichuan" },
    { code: "SD", name: "Shandong" }, { code: "SH", name: "Shanghai" },
    { code: "SN", name: "Shaanxi" }, { code: "SX", name: "Shanxi" },
    { code: "TJ", name: "Tianjin" }, { code: "XJ", name: "Xinjiang" },
    { code: "XZ", name: "Tibet" }, { code: "YN", name: "Yunnan" },
    { code: "ZJ", name: "Zhejiang" },
  ],
  JP: [
    { code: "01", name: "Hokkaido" }, { code: "02", name: "Aomori" },
    { code: "03", name: "Iwate" }, { code: "04", name: "Miyagi" },
    { code: "05", name: "Akita" }, { code: "06", name: "Yamagata" },
    { code: "07", name: "Fukushima" }, { code: "08", name: "Ibaraki" },
    { code: "09", name: "Tochigi" }, { code: "10", name: "Gunma" },
    { code: "11", name: "Saitama" }, { code: "12", name: "Chiba" },
    { code: "13", name: "Tokyo" }, { code: "14", name: "Kanagawa" },
    { code: "15", name: "Niigata" }, { code: "16", name: "Toyama" },
    { code: "17", name: "Ishikawa" }, { code: "18", name: "Fukui" },
    { code: "19", name: "Yamanashi" }, { code: "20", name: "Nagano" },
    { code: "21", name: "Gifu" }, { code: "22", name: "Shizuoka" },
    { code: "23", name: "Aichi" }, { code: "24", name: "Mie" },
    { code: "25", name: "Shiga" }, { code: "26", name: "Kyoto" },
    { code: "27", name: "Osaka" }, { code: "28", name: "Hyogo" },
    { code: "29", name: "Nara" }, { code: "30", name: "Wakayama" },
    { code: "31", name: "Tottori" }, { code: "32", name: "Shimane" },
    { code: "33", name: "Okayama" }, { code: "34", name: "Hiroshima" },
    { code: "35", name: "Yamaguchi" }, { code: "36", name: "Tokushima" },
    { code: "37", name: "Kagawa" }, { code: "38", name: "Ehime" },
    { code: "39", name: "Kochi" }, { code: "40", name: "Fukuoka" },
    { code: "41", name: "Saga" }, { code: "42", name: "Nagasaki" },
    { code: "43", name: "Kumamoto" }, { code: "44", name: "Oita" },
    { code: "45", name: "Miyazaki" }, { code: "46", name: "Kagoshima" },
    { code: "47", name: "Okinawa" },
  ],
  KR: [
    { code: "11", name: "Seoul" }, { code: "26", name: "Busan" },
    { code: "27", name: "Daegu" }, { code: "28", name: "Incheon" },
    { code: "29", name: "Gwangju" }, { code: "30", name: "Daejeon" },
    { code: "31", name: "Ulsan" }, { code: "41", name: "Gyeonggi" },
    { code: "42", name: "Gangwon" }, { code: "43", name: "North Chungcheong" },
    { code: "44", name: "South Chungcheong" }, { code: "45", name: "North Jeolla" },
    { code: "46", name: "South Jeolla" }, { code: "47", name: "North Gyeongsang" },
    { code: "48", name: "South Gyeongsang" }, { code: "49", name: "Jeju" },
    { code: "50", name: "Sejong" },
  ],
  TW: [
    { code: "TPE", name: "Taipei City" }, { code: "TAO", name: "Taoyuan" },
    { code: "HSZ", name: "Hsinchu City" }, { code: "TXG", name: "Taichung City" },
    { code: "CYI", name: "Chiayi City" }, { code: "TNN", name: "Tainan City" },
    { code: "KHH", name: "Kaohsiung City" }, { code: "TPQ", name: "New Taipei City" },
    { code: "ILA", name: "Yilan County" }, { code: "HSQ", name: "Hsinchu County" },
    { code: "MIA", name: "Miaoli County" }, { code: "CHA", name: "Changhua County" },
    { code: "NAN", name: "Nantou County" }, { code: "CYQ", name: "Chiayi County" },
    { code: "YUN", name: "Yunlin County" }, { code: "PIF", name: "Pingtung County" },
    { code: "TTT", name: "Taitung County" }, { code: "HUA", name: "Hualien County" },
    { code: "KIN", name: "Kinmen County" }, { code: "PEN", name: "Penghu County" },
  ],
  MY: [
    { code: "01", name: "Johor" }, { code: "02", name: "Kedah" },
    { code: "03", name: "Kelantan" }, { code: "04", name: "Melaka" },
    { code: "05", name: "Negeri Sembilan" }, { code: "06", name: "Pahang" },
    { code: "07", name: "Penang" }, { code: "08", name: "Perak" },
    { code: "09", name: "Perlis" }, { code: "10", name: "Sabah" },
    { code: "11", name: "Sarawak" }, { code: "12", name: "Selangor" },
    { code: "13", name: "Terengganu" }, { code: "14", name: "Kuala Lumpur" },
    { code: "15", name: "Labuan" }, { code: "16", name: "Putrajaya" },
  ],
  ID: [
    { code: "AC", name: "Aceh" }, { code: "BA", name: "Bali" },
    { code: "BB", name: "Bangka Belitung Islands" }, { code: "BT", name: "Banten" },
    { code: "BE", name: "Bengkulu" }, { code: "JT", name: "Central Java" },
    { code: "KT", name: "Central Kalimantan" }, { code: "ST", name: "Central Sulawesi" },
    { code: "JI", name: "East Java" }, { code: "KI", name: "East Kalimantan" },
    { code: "NT", name: "East Nusa Tenggara" }, { code: "GO", name: "Gorontalo" },
    { code: "JA", name: "Jambi" }, { code: "LA", name: "Lampung" },
    { code: "MA", name: "Maluku" }, { code: "MU", name: "North Maluku" },
    { code: "AC", name: "North Kalimantan" }, { code: "SU", name: "North Sulawesi" },
    { code: "NB", name: "West Nusa Tenggara" }, { code: "PA", name: "Papua" },
    { code: "PB", name: "Highland Papua" }, { code: "RI", name: "Riau" },
    { code: "KR", name: "Riau Islands" }, { code: "SG", name: "South Sulawesi" },
    { code: "SR", name: "West Sulawesi" }, { code: "SN", name: "South Sumatra" },
    { code: "SS", name: "South Papua" }, { code: "JA", name: "Southeast Sulawesi" },
    { code: "JB", name: "West Java" }, { code: "KB", name: "West Kalimantan" },
    { code: "SA", name: "West Papua" }, { code: "SL", name: "West Sumatra" },
    { code: "YO", name: "Yogyakarta" }, { code: "JK", name: "Jakarta" },
    { code: "BT", name: "Banten" },
  ],
  TH: [
    { code: "01", name: "Bangkok" }, { code: "02", name: "Samut Prakan" },
    { code: "03", name: "Nonthaburi" }, { code: "04", name: "Pathum Thani" },
    { code: "05", name: "Nakhon Pathom" }, { code: "06", name: "Samut Sakhon" },
    { code: "07", name: "Samut Songkhram" }, { code: "08", name: "Phetchaburi" },
    { code: "09", name: "Ratchaburi" }, { code: "10", name: "Kanchanaburi" },
    { code: "11", name: "Suphanburi" }, { code: "12", name: "Nakhon Nayok" },
    { code: "13", name: "Chachoengsao" }, { code: "14", name: "Prachinburi" },
    { code: "15", name: "Nakhon Ratchasima" }, { code: "16", name: "Buri Ram" },
    { code: "17", name: "Surin" }, { code: "18", name: "Si Sa Ket" },
    { code: "19", name: "Chonburi" }, { code: "20", name: "Rayong" },
    { code: "21", name: "Chanthaburi" }, { code: "22", name: "Trat" },
    { code: "23", name: "Chaiyaphum" }, { code: "24", name: "Nakhon Si Thammarat" },
    { code: "25", name: "Krabi" }, { code: "26", name: "Phang Nga" },
    { code: "27", name: "Ranong" }, { code: "28", name: "Surat Thani" },
    { code: "29", name: "Chumphon" }, { code: "30", name: "Prachuap Khiri Khan" },
    { code: "31", name: "Phetchabun" }, { code: "32", name: "Phitsanulok" },
    { code: "33", name: "Phichit" }, { code: "34", name: "Phra Nakhon Si Ayutthaya" },
    { code: "35", name: "Ang Thong" }, { code: "36", name: "Lopburi" },
    { code: "37", name: "Sing Buri" }, { code: "38", name: "Saraburi" },
    { code: "39", name: "Chai Nat" }, { code: "40", name: "Sukhothai" },
    { code: "41", name: "Tak" }, { code: "42", name: "Kamphaeng Phet" },
    { code: "43", name: "Phrae" }, { code: "44", name: "Uttaradit" },
    { code: "45", name: "Uthai Thani" }, { code: "46", name: "Phitsanulok" },
    { code: "47", name: "Phuket" }, { code: "48", name: "Narathiwat" },
    { code: "49", name: "Yala" }, { code: "50", name: "Pattani" },
    { code: "51", name: "Chiang Rai" }, { code: "52", name: "Mae Hong Son" },
    { code: "53", name: "Chiang Mai" }, { code: "54", name: "Lampang" },
    { code: "55", name: "Lamphun" }, { code: "56", name: "Udon Thani" },
    { code: "57", name: "Loei" }, { code: "58", name: "Sakon Nakhon" },
    { code: "59", name: "Nakhon Phanom" }, { code: "60", name: "Khon Kaen" },
    { code: "61", name: "Kalasin" }, { code: "62", name: "Roi Et" },
    { code: "63", name: "Maha Sarakham" }, { code: "64", name: "Nong Bua Lamphu" },
    { code: "65", name: "Nong Khai" }, { code: "66", name: "Bueng Kan" },
    { code: "67", name: "Ubon Ratchathani" }, { code: "68", name: "Amnat Charoen" },
    { code: "69", name: "Nan" }, { code: "70", name: "Phayao" },
    { code: "71", name: "Mukdahan" }, { code: "72", name: "Nakhon Sawan" },
    { code: "73", name: "Uthai Thani" }, { code: "74", name: "Lopburi" },
    { code: "75", name: "Phetchabun" }, { code: "76", name: "Chaiyaphum" },
    { code: "77", name: "Nakhon Si Thammarat" }, { code: "78", name: "Songkhla" },
    { code: "79", name: "Satun" }, { code: "80", name: "Trang" },
    { code: "81", name: "Phatthalung" }, { code: "82", name: "Pattani" },
    { code: "83", name: "Yala" }, { code: "84", name: "Narathiwat" },
    { code: "85", name: "Phuket" }, { code: "86", name: "Krabi" },
    { code: "87", name: "Nakhon Si Thammarat" }, { code: "88", name: "Surat Thani" },
    { code: "89", name: "Ranong" }, { code: "90", name: "Phang Nga" },
  ],
  VN: [
    { code: "01", name: "Hà Nội" }, { code: "02", name: "Hà Giang" },
    { code: "03", name: "Cao Bằng" }, { code: "04", name: "Bắc Kạn" },
    { code: "05", name: "Tuyên Quang" }, { code: "06", name: "Lào Cai" },
    { code: "07", name: "Điện Biên" }, { code: "08", name: "Lai Châu" },
    { code: "09", name: "Sơn La" }, { code: "10", name: "Yên Bái" },
    { code: "11", name: "Hòa Bình" }, { code: "12", name: "Lạng Sơn" },
    { code: "13", name: "Quảng Ninh" }, { code: "14", name: "Phú Thọ" },
    { code: "15", name: "Thái Nguyên" }, { code: "16", name: "Bắc Giang" },
    { code: "17", name: "Bắc Ninh" }, { code: "18", name: "Hải Dương" },
    { code: "19", name: "Hải Phòng" }, { code: "20", name: "Hưng Yên" },
    { code: "21", name: "Thái Bình" }, { code: "22", name: "Hà Nam" },
    { code: "23", name: "Nam Định" }, { code: "24", name: "Ninh Bình" },
    { code: "25", name: "Thanh Hóa" }, { code: "26", name: "Nghệ An" },
    { code: "27", name: "Hà Tĩnh" }, { code: "28", name: "Quảng Bình" },
    { code: "29", name: "Quảng Trị" }, { code: "30", name: "Thừa Thiên Huế" },
    { code: "31", name: "Đà Nẵng" }, { code: "32", name: "Quảng Nam" },
    { code: "33", name: "Quảng Ngãi" }, { code: "34", name: "Bình Định" },
    { code: "35", name: "Phú Yên" }, { code: "36", name: "Khánh Hòa" },
    { code: "37", name: "Ninh Thuận" }, { code: "38", name: "Bình Thuận" },
    { code: "39", name: "Kon Tum" }, { code: "40", name: "Gia Lai" },
    { code: "41", name: "Đắk Lắk" }, { code: "42", name: "Đắk Nông" },
    { code: "43", name: "Lâm Đồng" }, { code: "44", name: "Bình Phước" },
    { code: "45", name: "Bình Dương" }, { code: "46", name: "Đồng Nai" },
    { code: "47", name: "Bà Rịa-Vũng Tàu" }, { code: "48", name: "TP. Hồ Chí Minh" },
    { code: "49", name: "Tiền Giang" }, { code: "50", name: "Long An" },
    { code: "51", name: "Bến Tre" }, { code: "52", name: "Trà Vinh" },
    { code: "53", name: "Vĩnh Long" }, { code: "54", name: "Đồng Tháp" },
    { code: "55", name: "An Giang" }, { code: "56", name: "Kiên Giang" },
    { code: "57", name: "Cần Thơ" }, { code: "58", name: "Hậu Giang" },
    { code: "59", name: "Sóc Trăng" }, { code: "60", name: "Bạc Liêu" },
    { code: "61", name: "Cà Mau" },
  ],
  PH: [
    { code: "01", name: "Ilocos Region" }, { code: "02", name: "Cagayan Valley" },
    { code: "03", name: "Central Luzon" }, { code: "05", name: "Bicol Region" },
    { code: "06", name: "Western Visayas" }, { code: "07", name: "Central Visayas" },
    { code: "08", name: "Eastern Visayas" }, { code: "09", name: "Zamboanga Peninsula" },
    { code: "10", name: "Northern Mindanao" }, { code: "11", name: "Davao Region" },
    { code: "12", name: "SOCCSKSARGEN" }, { code: "13", name: "Caraga" },
    { code: "14", name: "Bangsamoro" }, { code: "40", name: "CALABARZON" },
    { code: "41", name: "MIMAROPA" }, { code: "NCR", name: "Metro Manila" },
    { code: "15", name: "Cordillera Administrative" },
  ],
  NZ: [
    { code: "AUK", name: "Auckland" }, { code: "BOP", name: "Bay of Plenty" },
    { code: "CAN", name: "Canterbury" }, { code: "GIS", name: "Gisborne" },
    { code: "HKB", name: "Hawke's Bay" }, { code: "MBH", name: "Marlborough" },
    { code: "MWT", name: "Manawatū-Whanganui" }, { code: "NSN", name: "Nelson" },
    { code: "NTL", name: "Northland" }, { code: "OTA", name: "Otago" },
    { code: "STL", name: "Southland" }, { code: "TAS", name: "Tasman" },
    { code: "TKI", name: "Taranaki" }, { code: "WGN", name: "Wellington" },
    { code: "WKO", name: "Waikato" }, { code: "WTC", name: "West Coast" },
  ],
  KZ: [
    { code: "ALA", name: "Almaty City" }, { code: "AST", name: "Astana City" },
    { code: "AKM", name: "Akmola" }, { code: "AKT", name: "Aktobe" },
    { code: "ALM", name: "Almaty Region" }, { code: "ATY", name: "Atyrau" },
    { code: "ZHA", name: "Zhambyl" }, { code: "KAR", name: "Karaganda" },
    { code: "KUS", name: "Kostanay" }, { code: "KZO", name: "Kyzylorda" },
    { code: "MAN", name: "Mangystau" }, { code: "PAV", name: "Pavlodar" },
    { code: "SEV", name: "North Kazakhstan" }, { code: "VOS", name: "East Kazakhstan" },
    { code: "YUZ", name: "South Kazakhstan" }, { code: "ZKO", name: "West Kazakhstan" },
    { code: "SHY", name: "Shymkent City" },
  ],
  UZ: [
    { code: "01", name: "Tashkent City" }, { code: "02", name: "Tashkent Region" },
    { code: "03", name: "Andijan" }, { code: "04", name: "Bukhara" },
    { code: "05", name: "Fergana" }, { code: "06", name: "Jizzakh" },
    { code: "07", name: "Khorezm" }, { code: "08", name: "Namangan" },
    { code: "09", name: "Navoiy" }, { code: "10", name: "Kashkadarya" },
    { code: "11", name: "Samarkand" }, { code: "12", name: "Surxondaryo" },
    { code: "13", name: "Syrdarya" }, { code: "14", name: "Karalkalpakstan" },
  ],
  AZ: [
    { code: "ABS", name: "Absheron" }, { code: "AGC", name: "Agjabedi" },
    { code: "AGM", name: "Agdam" }, { code: "AGS", name: "Agstafa" },
    { code: "AGA", name: "Aghdash" }, { code: "AST", name: "Astara" },
    { code: "BAB", name: "Babek" }, { code: "BAL", name: "Balakan" },
    { code: "BAR", name: "Barda" }, { code: "BEY", name: "Beylagan" },
    { code: "BIL", name: "Bilasuvar" }, { code: "CAB", name: "Jabrayil" },
    { code: "CAL", name: "Jalilabad" }, { code: "CUL", name: "Julfa" },
    { code: "DAS", name: "Dashkasan" }, { code: "FUZ", name: "Fuzuli" },
    { code: "GAD", name: "Gadabay" }, { code: "GOR", name: "Goranboy" },
    { code: "GOY", name: "Goychay" }, { code: "GYG", name: "Goygol" },
    { code: "HAC", name: "Hajigabul" }, { code: "IMI", name: "Imishli" },
    { code: "ISM", name: "Ismailli" }, { code: "KAL", name: "Kalbajar" },
    { code: "KUR", name: "Kurdamir" }, { code: "LAC", name: "Lachin" },
    { code: "LAN", name: "Lankaran" }, { code: "LER", name: "Lerik" },
    { code: "MAS", name: "Masalli" }, { code: "MIL", name: "Mingachevir" },
    { code: "NA", name: "Nakhchivan" }, { code: "NEF", name: "Neftchala" },
    { code: "OGU", name: "Oghuz" }, { code: "ORD", name: "Ordubad" },
    { code: "QAB", name: "Qabala" }, { code: "QAX", name: "Qakh" },
    { code: "QBA", name: "Guba" }, { code: "QBI", name: "Qubadli" },
    { code: "QOB", name: "Qusar" }, { code: "SAT", name: "Saatli" },
    { code: "SAB", name: "Sabirabad" }, { code: "SAD", name: "Sadarak" },
    { code: "SAH", name: "Shahbuz" }, { code: "SAK", name: "Shaki" },
    { code: "SAL", name: "Salyan" }, { code: "SMX", name: "Samukh" },
    { code: "SAR", name: "Sharur" }, { code: "SMI", name: "Shamakhi" },
    { code: "SKR", name: "Shamkir" }, { code: "SMR", name: "Shabran" },
    { code: "SIY", name: "Siazan" }, { code: "TAR", name: "Tartar" },
    { code: "TOV", name: "Tovuz" }, { code: "UCA", name: "Ujar" },
    { code: "YAR", name: "Yardymli" }, { code: "YEV", name: "Yevlakh" },
    { code: "ZAN", name: "Zangilan" }, { code: "ZAQ", name: "Zaqatala" },
    { code: "ZAR", name: "Zardab" }, { code: "BA", name: "Baku" },
  ],
  GE: [
    { code: "AB", name: "Abkhazia" }, { code: "AJ", name: "Adjara" },
    { code: "GU", name: "Guria" }, { code: "IM", name: "Imereti" },
    { code: "KA", name: "Kakheti" }, { code: "KK", name: "Kvemo Kartli" },
    { code: "MM", name: "Mtskheta-Mtianeti" }, { code: "RL", name: "Racha-Lechkhumi" },
    { code: "SJ", name: "Samegrelo-Zemo Svaneti" }, { code: "SK", name: "Samtskhe-Javakheti" },
    { code: "SR", name: "Shida Kartli" }, { code: "TB", name: "Tbilisi" },
    { code: "GU", name: "Guria" },
  ],
  AM: [
    { code: "AG", name: "Aragatsotn" }, { code: "AR", name: "Ararat" },
    { code: "AV", name: "Armavir" }, { code: "ER", name: "Yerevan" },
    { code: "GR", name: "Gegharkunik" }, { code: "KT", name: "Kotayk" },
    { code: "LO", name: "Lori" }, { code: "SH", name: "Shirak" },
    { code: "SU", name: "Syunik" }, { code: "TV", name: "Tavush" },
    { code: "VD", name: "Vayots Dzor" },
  ],
  BY: [
    { code: "BR", name: "Brest" }, { code: "HO", name: "Gomel" },
    { code: "HR", name: "Grodno" }, { code: "MA", name: "Mogilev" },
    { code: "MI", name: "Minsk" }, { code: "VI", name: "Vitebsk" },
    { code: "HM", name: "Minsk City" },
  ],
  MD: [
    { code: "AN", name: "Anenii Noi" }, { code: "BA", name: "Bălți" },
    { code: "BD", name: "Bender" }, { code: "BR", name: "Briceni" },
    { code: "BS", name: "Basarabeasca" }, { code: "CA", name: "Cahul" },
    { code: "CT", name: "Cantemir" }, { code: "CH", name: "Chișinău" },
    { code: "CZ", name: "Călărași" }, { code: "ED", name: "Edineț" },
    { code: "FA", name: "Fălești" }, { code: "FL", name: "Florești" },
    { code: "GL", name: "Glodeni" }, { code: "HI", name: "Hîncești" },
    { code: "IA", name: "Ialoveni" }, { code: "LE", name: "Leova" },
    { code: "NI", name: "Nisporeni" }, { code: "OC", name: "Ocnița" },
    { code: "OR", name: "Orhei" }, { code: "RE", name: "Rezina" },
    { code: "SI", name: "Sîngerei" }, { code: "SO", name: "Soroca" },
    { code: "ST", name: "Strășeni" }, { code: "SD", name: "Șoldănești" },
    { code: "SR", name: "Sîngerei" }, { code: "TA", name: "Taraclia" },
    { code: "TE", name: "Telenești" }, { code: "UN", name: "Ungheni" },
  ],
  RS: [
    { code: "00", name: "Belgrade" }, { code: "01", name: "North Bačka" },
    { code: "02", name: "Central Banat" }, { code: "03", name: "North Banat" },
    { code: "04", name: "South Banat" }, { code: "05", name: "West Bačka" },
    { code: "06", name: "South Bačka" }, { code: "07", name: "Srem" },
    { code: "08", name: "Mačva" }, { code: "09", name: "Kolubara" },
    { code: "10", name: "Podunavlje" }, { code: "11", name: "Braničevo" },
    { code: "12", name: "Šumadija" }, { code: "13", name: "Pomoravlje" },
    { code: "14", name: "Bor" }, { code: "15", name: "Zaječar" },
    { code: "16", name: "Zlatibor" }, { code: "17", name: "Moravica" },
    { code: "18", name: "Raška" }, { code: "19", name: "Rasina" },
    { code: "20", name: "Nišava" }, { code: "21", name: "Toplica" },
    { code: "22", name: "Pirot" }, { code: "23", name: "Jablanica" },
    { code: "24", name: "Pčinja" }, { code: "25", name: "Kosovo" },
    { code: "26", name: "Peć" }, { code: "27", name: "Prizren" },
    { code: "28", name: "Kosovska Mitrovica" }, { code: "29", name: "Kosovo-Pomoravlje" },
    { code: "KM", name: "Kosovo-Mitrovica" },
  ],
  BA: [
    { code: "BRC", name: "Brčko District" }, { code: "BIH", name: "Federation of Bosnia and Herzegovina" },
    { code: "SRP", name: "Republika Srpska" },
  ],
  MK: [
    { code: "01", name: "Aerodrom" }, { code: "02", name: "Aračinovo" },
    { code: "03", name: "Berovo" }, { code: "04", name: "Bitola" },
    { code: "05", name: "Bogdanci" }, { code: "06", name: "Bogovinje" },
    { code: "07", name: "Bosilovo" }, { code: "08", name: "Brvenica" },
    { code: "09", name: "Butel" }, { code: "10", name: "Valandovo" },
    { code: "11", name: "Vasilevo" }, { code: "12", name: "Vevčani" },
    { code: "13", name: "Veles" }, { code: "14", name: "Vinica" },
    { code: "15", name: "Vraneš" },
  ],
  AL: [
    { code: "01", name: "Berat" }, { code: "02", name: "Durrës" },
    { code: "03", name: "Elbasan" }, { code: "04", name: "Fier" },
    { code: "05", name: "Gjirokastër" }, { code: "06", name: "Korçë" },
    { code: "07", name: "Kukës" }, { code: "08", name: "Lezhë" },
    { code: "09", name: "Dibër" }, { code: "10", name: "Shkodër" },
    { code: "11", name: "Tirana" }, { code: "12", name: "Vlorë" },
  ],
  ME: [
    { code: "01", name: "Andrijevica" }, { code: "02", name: "Bar" },
    { code: "03", name: "Berane" }, { code: "04", name: "Bijelo Polje" },
    { code: "05", name: "Budva" }, { code: "06", name: "Cetinje" },
    { code: "07", name: "Danilovgrad" }, { code: "08", name: "Gusinje" },
    { code: "09", name: "Kolašin" }, { code: "10", name: "Kotor" },
    { code: "11", name: "Mojkovac" }, { code: "12", name: "Nikšić" },
    { code: "13", name: "Old Royal Capital Cetinje" }, { code: "14", name: "Petnjica" },
    { code: "15", name: "Plav" }, { code: "16", name: "Plužine" },
    { code: "17", name: "Pljevlja" }, { code: "18", name: "Podgorica" },
    { code: "19", name: "Rožaje" }, { code: "20", name: "Šavnik" },
    { code: "21", name: "Tivat" }, { code: "22", name: "Ulcinj" },
    { code: "23", name: "Žabljak" },
  ],
  FJ: [
    { code: "01", name: "Ba" }, { code: "02", name: "Bua" },
    { code: "03", name: "Cakaudrove" }, { code: "04", name: "Kadavu" },
    { code: "05", name: "Lau" }, { code: "06", name: "Lomaiviti" },
    { code: "07", name: "Macuata" }, { code: "08", name: "Nadroga-Navosa" },
    { code: "09", name: "Naitasiri" }, { code: "10", name: "Namosi" },
    { code: "11", name: "Ra" }, { code: "12", name: "Rewa" },
    { code: "13", name: "Serua" }, { code: "14", name: "Tailevu" },
    { code: "15", name: "Rotuma" },
  ],
  TH_NA: [],
  SG: [],
  HK: [],
  MO: [],
  LU_NA: [],
  LI: [],
  MC: [],
  VA: [],
  SM: [],
  AD: [],
  BW: [
    { code: "CE", name: "Central" }, { code: "GH", name: "Ghanzi" },
    { code: "KG", name: "Kgalagadi" }, { code: "KL", name: "Kgatleng" },
    { code: "KW", name: "Kweneng" }, { code: "NE", name: "North-East" },
    { code: "NW", name: "North-West" }, { code: "SO", name: "Southern" },
    { code: "SE", name: "South-East" },
  ],
  NA: [
    { code: "CA", name: "Zambezi" }, { code: "ER", name: "Erongo" },
    { code: "HA", name: "Hardap" }, { code: "KA", name: "Karas" },
    { code: "KE", name: "Kavango East" }, { code: "KW", name: "Kavango West" },
    { code: "KH", name: "Khomas" }, { code: "KU", name: "Kunene" },
    { code: "OW", name: "Ohangwena" }, { code: "OH", name: "Omaheke" },
    { code: "ON", name: "Oshana" }, { code: "OT", name: "Oshikoto" },
    { code: "OD", name: "Otjozondjupa" },
  ],
  GH: [
    { code: "AH", name: "Ashanti" }, { code: "BA", name: "Bono Ahafo" },
    { code: "BO", name: "Bono East" }, { code: "AE", name: "Ahafo" },
    { code: "CP", name: "Central" }, { code: "EP", name: "Eastern" },
    { code: "AA", name: "Greater Accra" }, { code: "NP", name: "North East" },
    { code: "NR", name: "Northern" }, { code: "OT", name: "Oti" },
    { code: "SV", name: "Savannah" }, { code: "UE", name: "Upper East" },
    { code: "UW", name: "Upper West" }, { code: "WP", name: "Western" },
    { code: "WN", name: "Western North" }, { code: "VR", name: "Volta" },
  ],
  SN: [
    { code: "DK", name: "Dakar" }, { code: "DB", name: "Diourbel" },
    { code: "FK", name: "Fatick" }, { code: "KA", name: "Kaffrine" },
    { code: "KL", name: "Kaolack" }, { code: "KE", name: "Kédougou" },
    { code: "KD", name: "Kolda" }, { code: "LG", name: "Louga" },
    { code: "MT", name: "Matam" }, { code: "SL", name: "Saint-Louis" },
    { code: "SE", name: "Sédhiou" }, { code: "TC", name: "Tambacounda" },
    { code: "TH", name: "Thiès" }, { code: "ZG", name: "Ziguinchor" },
  ],
  TZ: [
    { code: "01", name: "Arusha" }, { code: "02", name: "Dar es Salaam" },
    { code: "03", name: "Dodoma" }, { code: "04", name: "Iringa" },
    { code: "05", name: "Kagera" }, { code: "06", name: "Pemba North" },
    { code: "07", name: "Pemba South" }, { code: "08", name: "Kigoma" },
    { code: "09", name: "Kilimanjaro" }, { code: "10", name: "Lindi" },
    { code: "11", name: "Manyara" }, { code: "12", name: "Mara" },
    { code: "13", name: "Mbeya" }, { code: "14", name: "Mjini Magharibi" },
    { code: "15", name: "Morogoro" }, { code: "16", name: "Mtwara" },
    { code: "17", name: "Mwanza" }, { code: "18", name: "Njombe" },
    { code: "19", name: "Pwani" }, { code: "20", name: "Rukwa" },
    { code: "21", name: "Ruvuma" }, { code: "22", name: "Shinyanga" },
    { code: "23", name: "Simiyu" }, { code: "24", name: "Singida" },
    { code: "25", name: "Tabora" }, { code: "26", name: "Tanga" },
    { code: "27", name: "Geita" }, { code: "28", name: "Katavi" },
    { code: "29", name: "Songwe" },
  ],
  UG: [
    { code: "101", name: "Kampala" }, { code: "102", name: "Buikwe" },
    { code: "103", name: "Bukomansimbi" }, { code: "104", name: "Butambala" },
    { code: "105", name: "Buvuma" }, { code: "106", name: "Gomba" },
    { code: "107", name: "Kalangala" }, { code: "108", name: "Kalungu" },
    { code: "109", name: "Kayunga" }, { code: "110", name: "Kiboga" },
    { code: "111", name: "Kyankwanzi" }, { code: "112", name: "Lwengo" },
    { code: "113", name: "Lyantonde" }, { code: "114", name: "Masaka" },
    { code: "115", name: "Mityana" }, { code: "116", name: "Mpigi" },
    { code: "117", name: "Mubende" }, { code: "118", name: "Mukono" },
    { code: "119", name: "Nakaseke" }, { code: "120", name: "Nakasongola" },
    { code: "121", name: "Rakai" }, { code: "122", name: "Sembabule" },
    { code: "123", name: "Wakiso" },
  ],
  RW: [
    { code: "01", name: "Kigali City" }, { code: "02", name: "Southern" },
    { code: "03", name: "Western" }, { code: "04", name: "Northern" },
    { code: "05", name: "Eastern" },
  ],
  CM: [
    { code: "AD", name: "Adamawa" }, { code: "CE", name: "Centre" },
    { code: "ES", name: "East" }, { code: "EN", name: "Far North" },
    { code: "LT", name: "Littoral" }, { code: "NO", name: "North" },
    { code: "NW", name: "North-West" }, { code: "SU", name: "South" },
    { code: "SW", name: "South-West" }, { code: "OU", name: "West" },
  ],
  AO: [
    { code: "BGO", name: "Bengo" }, { code: "BGU", name: "Benguela" },
    { code: "BIE", name: "Bié" }, { code: "CAB", name: "Cabinda" },
    { code: "CCU", name: "Cuanza Sul" }, { code: "CNO", name: "Cuanza Norte" },
    { code: "CNN", name: "Cunene" }, { code: "HUA", name: "Huambo" },
    { code: "HUI", name: "Huíla" }, { code: "LUA", name: "Luanda" },
    { code: "LNO", name: "Lunda Norte" }, { code: "LSU", name: "Lunda Sul" },
    { code: "MAL", name: "Malanje" }, { code: "MOX", name: "Moxico" },
    { code: "NAM", name: "Namibe" }, { code: "UIG", name: "Uíge" },
    { code: "ZAI", name: "Zaire" },
  ],
  DZ: [
    { code: "01", name: "Adrar" }, { code: "02", name: "Chlef" },
    { code: "03", name: "Laghouat" }, { code: "04", name: "Oum El Bouaghi" },
    { code: "05", name: "Batna" }, { code: "06", name: "Béjaïa" },
    { code: "07", name: "Biskra" }, { code: "08", name: "Béchar" },
    { code: "09", name: "Blida" }, { code: "10", name: "Bouira" },
    { code: "11", name: "Tamanrasset" }, { code: "12", name: "Tébessa" },
    { code: "13", name: "Tlemcen" }, { code: "14", name: "Tiaret" },
    { code: "15", name: "Tizi Ouzou" }, { code: "16", name: "Alger" },
    { code: "17", name: "Djelfa" }, { code: "18", name: "Jijel" },
    { code: "19", name: "Sétif" }, { code: "20", name: "Saïda" },
    { code: "21", name: "Skikda" }, { code: "22", name: "Sidi Bel Abbès" },
    { code: "23", name: "Annaba" }, { code: "24", name: "Guelma" },
    { code: "25", name: "Constantine" }, { code: "26", name: "Médéa" },
    { code: "27", name: "Mostaganem" }, { code: "28", name: "M'Sila" },
    { code: "29", name: "Mascara" }, { code: "30", name: "Ouargla" },
    { code: "31", name: "Oran" }, { code: "32", name: "El Bayadh" },
    { code: "33", name: "Illizi" }, { code: "34", name: "Bordj Bou Arréridj" },
    { code: "35", name: "Boumerdès" }, { code: "36", name: "El Tarf" },
    { code: "37", name: "Tindouf" }, { code: "38", name: "Tissemsilt" },
    { code: "39", name: "El Oued" }, { code: "40", name: "Khenchela" },
    { code: "41", name: "Souk Ahras" }, { code: "42", name: "Tipaza" },
    { code: "43", name: "Mila" }, { code: "44", name: "Aïn Defla" },
    { code: "45", name: "Naâma" }, { code: "46", name: "Aïn Témouchent" },
    { code: "47", name: "Ghardaïa" }, { code: "48", name: "Relizane" },
  ],
  TN: [
    { code: "01", name: "Tunis" }, { code: "02", name: "Ariana" },
    { code: "03", name: "Ben Arous" }, { code: "04", name: "Manouba" },
    { code: "05", name: "Nabeul" }, { code: "06", name: "Zaghouan" },
    { code: "07", name: "Bizerte" }, { code: "08", name: "Béja" },
    { code: "09", name: "Jendouba" }, { code: "10", name: "Le Kef" },
    { code: "11", name: "Siliana" }, { code: "12", name: "Sousse" },
    { code: "13", name: "Monastir" }, { code: "14", name: "Mahdia" },
    { code: "15", name: "Sfax" }, { code: "16", name: "Gafsa" },
    { code: "17", name: "Tozeur" }, { code: "18", name: "Kebili" },
    { code: "19", name: "Gabès" }, { code: "20", name: "Medenine" },
    { code: "21", name: "Tataouine" }, { code: "22", name: "Kairouan" },
    { code: "23", name: "Kasserine" }, { code: "24", name: "Sidi Bouzid" },
  ],
  TH_NA2: [],
  IR: [
    { code: "01", name: "Alborz" }, { code: "02", name: "Ardabil" },
    { code: "03", name: "Bushehr" }, { code: "04", name: "Chaharmahal and Bakhtiari" },
    { code: "05", name: "East Azerbaijan" }, { code: "06", name: "Isfahan" },
    { code: "07", name: "Fars" }, { code: "08", name: "Gilan" },
    { code: "09", name: "Golestan" }, { code: "10", name: "Hamadan" },
    { code: "11", name: "Hormozgan" }, { code: "12", name: "Ilam" },
    { code: "13", name: "Kerman" }, { code: "14", name: "Kermanshah" },
    { code: "15", name: "Khuzestan" }, { code: "16", name: "Kohgiluyeh and Boyer-Ahmad" },
    { code: "17", name: "Kurdistan" }, { code: "18", name: "Lorestan" },
    { code: "19", name: "Markazi" }, { code: "20", name: "Mazandaran" },
    { code: "21", name: "North Khorasan" }, { code: "22", name: "Qazvin" },
    { code: "23", name: "Qom" }, { code: "24", name: "Razavi Khorasan" },
    { code: "25", name: "Semnan" }, { code: "26", name: "Sistan and Baluchestan" },
    { code: "27", name: "South Khorasan" }, { code: "28", name: "Tehran" },
    { code: "29", name: "Yazd" }, { code: "30", name: "Zanjan" },
  ],
  IQ: [
    { code: "AN", name: "Al Anbar" }, { code: "BA", name: "Babil" },
    { code: "BB", name: "Baghdad" }, { code: "BAS", name: "Basra" },
    { code: "DA", name: "Dhi Qar" }, { code: "DI", name: "Diyala" },
    { code: "DQ", name: "Al-Qādisiyyah" }, { code: "KA", name: "Karbala" },
    { code: "KI", name: "Kirkuk" }, { code: "MA", name: "Maysan" },
    { code: "MU", name: "Muthanna" }, { code: "NA", name: "Najaf" },
    { code: "NI", name: "Nineveh" }, { code: "QA", name: "Saladin" },
    { code: "SD", name: "Sulaymaniyah" }, { code: "WA", name: "Wasit" },
    { code: "ER", name: "Erbil" }, { code: "DH", name: "Duhok" },
    { code: "HL", name: "Halabja" },
  ],
  JO: [
    { code: "AJ", name: "Ajloun" }, { code: "AM", name: "Amman" },
    { code: "AQ", name: "Aqaba" }, { code: "BA", name: "Balqa" },
    { code: "IR", name: "Irbid" }, { code: "JA", name: "Jerash" },
    { code: "KA", name: "Karak" }, { code: "MA", name: "Madaba" },
    { code: "MD", name: "Mafraq" }, { code: "MN", name: "Manama" },
    { code: "AT", name: "Tafilah" }, { code: "AZ", name: "Zarqa" },
  ],
  LB: [
    { code: "AK", name: "Akkar" }, { code: "AS", name: "North Lebanon" },
    { code: "BA", name: "Baalbek-Hermel" }, { code: "BH", name: "Beirut" },
    { code: "JA", name: "South Lebanon" }, { code: "JL", name: "Mount Lebanon" },
    { code: "NA", name: "Nabatieh" },
  ],
  KW_NA: [],
  SY: [
    { code: "01", name: "Damascus" }, { code: "02", name: "Rif Dimashq" },
    { code: "03", name: "Quneitra" }, { code: "04", name: "Daraa" },
    { code: "05", name: "As-Suwayda" }, { code: "06", name: "Homs" },
    { code: "07", name: "Tartus" }, { code: "08", name: "Latakia" },
    { code: "09", name: "Hama" }, { code: "10", name: "Idlib" },
    { code: "11", name: "Aleppo" }, { code: "12", name: "Raqqa" },
    { code: "13", name: "Deir ez-Zor" }, { code: "14", name: "Hasakah" },
  ],
  YE: [
    { code: "AD", name: "Aden" }, { code: "AM", name: "Amran" },
    { code: "AB", name: "Abyan" }, { code: "DH", name: "Dhamar" },
    { code: "HD", name: "Hadramaut" }, { code: "HJ", name: "Hajjah" },
    { code: "HU", name: "Al Hudaydah" }, { code: "IB", name: "Ibb" },
    { code: "LA", name: "Lahij" }, { code: "MA", name: "Marib" },
    { code: "MR", name: "Al Mahrah" }, { code: "MW", name: "Al Mahwit" },
    { code: "SD", name: "Saada" }, { code: "SN", name: "San'a" },
    { code: "SH", name: "Shabwah" }, { code: "TA", name: "Taiz" },
    { code: "DA", name: "Dali" }, { code: "RA", name: "Raimah" },
    { code: "SA", name: "Socotra" },
  ],
  AF: [
    { code: "BAL", name: "Balkh" }, { code: "BAM", name: "Bamyan" },
    { code: "DAY", name: "Daykundi" }, { code: "FRA", name: "Farah" },
    { code: "FYB", name: "Faryab" }, { code: "GHA", name: "Ghazni" },
    { code: "GHO", name: "Ghor" }, { code: "HEL", name: "Helmand" },
    { code: "HER", name: "Herat" }, { code: "JOW", name: "Jowzjan" },
    { code: "KAB", name: "Kabul" }, { code: "KAN", name: "Kandahar" },
    { code: "KAP", name: "Kapisa" }, { code: "KDZ", name: "Kunduz" },
    { code: "KHO", name: "Khost" }, { code: "KNR", name: "Kunar" },
    { code: "LAG", name: "Laghman" }, { code: "LOG", name: "Logar" },
    { code: "NAN", name: "Nangarhar" }, { code: "NIM", name: "Nimruz" },
    { code: "NUR", name: "Nuristan" }, { code: "PIA", name: "Paktia" },
    { code: "PKA", name: "Paktika" }, { code: "PAN", name: "Panjshir" },
    { code: "PAR", name: "Parwan" }, { code: "SAM", name: "Samangan" },
    { code: "SAR", name: "Sar-e Pol" }, { code: "TAK", name: "Takhar" },
    { code: "URU", name: "Uruzgan" }, { code: "ZAB", name: "Zabul" },
    { code: "BAD", name: "Badakhshan" }, { code: "BDG", name: "Badghis" },
    { code: "BDS", name: "Baghlan" },
  ],
  NP: [
    { code: "P1", name: "Koshi" }, { code: "P2", name: "Madhesh" },
    { code: "P3", name: "Bagmati" }, { code: "P4", name: "Gandaki" },
    { code: "P5", name: "Lumbini" }, { code: "P6", name: "Karnali" },
    { code: "P7", name: "Sudurpashchim" },
  ],
  LK: [
    { code: "1", name: "Basnahira" }, { code: "2", name: "Central" },
    { code: "3", name: "Dakunu" }, { code: "4", name: "Negenahira" },
    { code: "5", name: "Wayamba" }, { code: "6", name: "North Central" },
    { code: "7", name: "Uva" }, { code: "8", name: "Sabaragamuwa" },
    { code: "9", name: "East" },
  ],
  MM: [
    { code: "01", name: "Sagaing" }, { code: "02", name: "Bago" },
    { code: "03", name: "Magway" }, { code: "04", name: "Mandalay" },
    { code: "05", name: "Tanintharyi" }, { code: "06", name: "Yangon" },
    { code: "07", name: "Ayeyarwady" }, { code: "11", name: "Kachin" },
    { code: "12", name: "Kayah" }, { code: "13", name: "Kayin" },
    { code: "14", name: "Chin" }, { code: "15", name: "Mon" },
    { code: "16", name: "Rakhine" }, { code: "17", name: "Shan" },
    { code: "18", name: "Naypyidaw" },
  ],
  KH: [
    { code: "01", name: "Banteay Meanchey" }, { code: "02", name: "Battambang" },
    { code: "03", name: "Kampong Cham" }, { code: "04", name: "Kampong Chhnang" },
    { code: "05", name: "Kampong Speu" }, { code: "06", name: "Kampong Thom" },
    { code: "07", name: "Kampot" }, { code: "08", name: "Kandal" },
    { code: "09", name: "Kep" }, { code: "10", name: "Kratie" },
    { code: "11", name: "Mondulkiri" }, { code: "12", name: "Phnom Penh" },
    { code: "13", name: "Preah Vihear" }, { code: "14", name: "Prey Veng" },
    { code: "15", name: "Pursat" }, { code: "16", name: "Ratanakiri" },
    { code: "17", name: "Siem Reap" }, { code: "18", name: "Preah Sihanouk" },
    { code: "19", name: "Stung Treng" }, { code: "20", name: "Svay Rieng" },
    { code: "21", name: "Takeo" }, { code: "22", name: "Oddar Meanchey" },
    { code: "23", name: "Kep" }, { code: "24", name: "Pailin" },
    { code: "25", name: "Tboung Khmum" },
  ],
  LA: [
    { code: "AT", name: "Attapeu" }, { code: "BK", name: "Bokeo" },
    { code: "BL", name: "Bolikhamsai" }, { code: "CH", name: "Champasak" },
    { code: "HO", name: "Houaphanh" }, { code: "KH", name: "Khammuan" },
    { code: "LM", name: "Luang Namtha" }, { code: "LP", name: "Luang Prabang" },
    { code: "OU", name: "Oudomxay" }, { code: "PH", name: "Phongsaly" },
    { code: "SL", name: "Salavan" }, { code: "SV", name: "Savannakhet" },
    { code: "VI", name: "Vientiane Province" }, { code: "VT", name: "Vientiane" },
    { code: "XA", name: "Sainyabuli" }, { code: "XE", name: "Sekong" },
    { code: "XI", name: "Xieng Khuang" },
  ],
  BD: [
    { code: "01", name: "Barishal" }, { code: "02", name: "Chattogram" },
    { code: "03", name: "Dhaka" }, { code: "04", name: "Khulna" },
    { code: "05", name: "Rajshahi" }, { code: "06", name: "Rangpur" },
    { code: "07", name: "Sylhet" }, { code: "08", name: "Mymensingh" },
  ],
  BY_NA: [],
  ET: [
    { code: "AA", name: "Addis Ababa" }, { code: "AF", name: "Afar" },
    { code: "AM", name: "Amhara" }, { code: "BE", name: "Benishangul-Gumuz" },
    { code: "DD", name: "Dire Dawa" }, { code: "GA", name: "Gambela" },
    { code: "HA", name: "Harari" }, { code: "OR", name: "Oromia" },
    { code: "SO", name: "Somali" }, { code: "SN", name: "Southern Nations" },
    { code: "TI", name: "Tigray" },
  ],
  CD: [
    { code: "BC", name: "Tshopo" }, { code: "BN", name: "North Kivu" },
    { code: "BK", name: "South Kivu" }, { code: "EQ", name: "Équateur" },
    { code: "HK", name: "Haut-Katanga" }, { code: "HL", name: "Haut-Lomami" },
    { code: "IT", name: "Ituri" }, { code: "KC", name: "Kasaï Central" },
    { code: "KG", name: "Kasaï" }, { code: "KN", name: "Kwango" },
    { code: "KS", name: "Kasai" }, { code: "MA", name: "Maniema" },
    { code: "NK", name: "Nord-Ubangi" }, { code: "SA", name: "Sankuru" },
    { code: "SK", name: "Sud-Kivu" }, { code: "TA", name: "Tanganyika" },
    { code: "TO", name: "Tshopo" }, { code: "TU", name: "Tshuapa" },
    { code: "KB", name: "Kwilu" }, { code: "KG", name: "Kongo Central" },
    { code: "HU", name: "Haut-Uele" }, { code: "LO", name: "Lomami" },
    { code: "MB", name: "Mai-Ndombe" }, { code: "MO", name: "Mongala" },
    { code: "NU", name: "Nord-Ubangi" }, { code: "SU", name: "Sud-Ubangi" },
    { code: "LO", name: "Lower Uele" }, { code: "BU", name: "Bunia" },
  ],
  SD: [
    { code: "RS", name: "Red Sea" }, { code: "GZ", name: "Al Jazirah" },
    { code: "KH", name: "Khartoum" }, { code: "GD", name: "Gedaref" },
    { code: "NR", name: "Northern" }, { code: "NW", name: "North Darfur" },
    { code: "SD", name: "South Darfur" }, { code: "WD", name: "West Darfur" },
    { code: "CA", name: "Central Darfur" }, { code: "ED", name: "East Darfur" },
    { code: "KN", name: "North Kordofan" }, { code: "SK", name: "South Kordofan" },
    { code: "WK", name: "West Kordofan" }, { code: "NB", name: "Blue Nile" },
    { code: "DW", name: "White Nile" }, { code: "NS", name: "Northern State" },
    { code: "KE", name: "Kassala" }, { code: "SE", name: "Sennar" },
    { code: "KZ", name: "Khartoum" },
  ],
  LY: [
    { code: "BA", name: "Benghazi" }, { code: "BU", name: "Butnan" },
    { code: "DR", name: "Derna" }, { code: "GT", name: "Ghat" },
    { code: "JA", name: "Jabal al Akhdar" }, { code: "JB", name: "Jafara" },
    { code: "JI", name: "Jufra" }, { code: "KU", name: "Kufra" },
    { code: "MJ", name: "Marj" }, { code: "MB", name: "Murqub" },
    { code: "MI", name: "Misrata" }, { code: "NQ", name: "Nuqat al Khams" },
    { code: "SB", name: "Sabha" }, { code: "SR", name: "Sirte" },
    { code: "TB", name: "Tajoura" }, { code: "TL", name: "Tarabulus" },
    { code: "WA", name: "Wadi al Hayaa" }, { code: "WD", name: "Wadi al Shati" },
    { code: "ZA", name: "Zawiya" }, { code: "ZU", name: "Zliten" },
    { code: "WD", name: "Tripoli" },
  ],
  JM: [
    { code: "01", name: "Kingston" }, { code: "02", name: "Saint Andrew" },
    { code: "03", name: "Saint Thomas" }, { code: "04", name: "Portland" },
    { code: "05", name: "Saint Mary" }, { code: "06", name: "Saint Ann" },
    { code: "07", name: "Trelawny" }, { code: "08", name: "Saint James" },
    { code: "09", name: "Hanover" }, { code: "10", name: "Westmoreland" },
    { code: "11", name: "Saint Elizabeth" }, { code: "12", name: "Manchester" },
    { code: "13", name: "Clarendon" }, { code: "14", name: "Saint Catherine" },
  ],
  TT: [
    { code: "CTT", name: "Couva-Tabaquite-Talparo" }, { code: "DMN", name: "Diego Martin" },
    { code: "PED", name: "Penal-Debe" }, { code: "PRI", name: "Princes Town" },
    { code: "RCM", name: "Rio Claro-Mayaro" }, { code: "SIP", name: "Siparia" },
    { code: "SGE", name: "Sangre Grande" }, { code: "SJL", name: "San Juan-Laventille" },
    { code: "TUP", name: "Tunapuna-Piarco" }, { code: "ARI", name: "Arima" },
    { code: "CHA", name: "Chaguanas" }, { code: "PTF", name: "Point Fortin" },
    { code: "POS", name: "Port of Spain" }, { code: "TOB", name: "Tobago" },
  ],
  HT: [
    { code: "AR", name: "Artibonite" }, { code: "CE", name: "Centre" },
    { code: "GA", name: "Grand'Anse" }, { code: "NI", name: "Nippes" },
    { code: "ND", name: "North" }, { code: "NE", name: "North-East" },
    { code: "OU", name: "West" }, { code: "SD", name: "South" },
    { code: "SE", name: "South-East" }, { code: "NI", name: "Nippes" },
  ],
  HN: [
    { code: "AT", name: "Atlántida" }, { code: "CL", name: "Colón" },
    { code: "CM", name: "Comayagua" }, { code: "CP", name: "Copán" },
    { code: "CR", name: "Cortés" }, { code: "CH", name: "Choluteca" },
    { code: "EP", name: "El Paraíso" }, { code: "FM", name: "Francisco Morazán" },
    { code: "GD", name: "Gracias a Dios" }, { code: "IN", name: "Intibucá" },
    { code: "IB", name: "Islas de la Bahía" }, { code: "LP", name: "La Paz" },
    { code: "LE", name: "Lempira" }, { code: "OC", name: "Ocotepeque" },
    { code: "OL", name: "Olancho" }, { code: "SB", name: "Santa Bárbara" },
    { code: "VA", name: "Valle" }, { code: "YO", name: "Yoro" },
  ],
  NI: [
    { code: "BO", name: "Boaco" }, { code: "CA", name: "Carazo" },
    { code: "CI", name: "Chinandega" }, { code: "CO", name: "Chontales" },
    { code: "ES", name: "Estelí" }, { code: "GR", name: "Granada" },
    { code: "JI", name: "Jinotega" }, { code: "LE", name: "León" },
    { code: "MD", name: "Madriz" }, { code: "MN", name: "Managua" },
    { code: "MS", name: "Masaya" }, { code: "MT", name: "Matagalpa" },
    { code: "NS", name: "Nueva Segovia" }, { code: "RI", name: "Rivas" },
    { code: "SJ", name: "Río San Juan" }, { code: "AN", name: "North Caribbean Coast" },
    { code: "AS", name: "South Caribbean Coast" },
  ],
  SV: [
    { code: "AH", name: "Ahuachapán" }, { code: "CA", name: "Cabañas" },
    { code: "CH", name: "Chalatenango" }, { code: "CU", name: "Cuscatlán" },
    { code: "LI", name: "La Libertad" }, { code: "MO", name: "Morazán" },
    { code: "PA", name: "La Paz" }, { code: "SA", name: "Santa Ana" },
    { code: "SM", name: "San Miguel" }, { code: "SO", name: "Sonsonate" },
    { code: "SS", name: "San Salvador" }, { code: "SV", name: "San Vicente" },
    { code: "UN", name: "La Unión" }, { code: "US", name: "Usulután" },
  ],
  GT_NA: [],
  CU: [
    { code: "01", name: "Pinar del Río" }, { code: "02", name: "Artemisa" },
    { code: "03", name: "Mayabeque" }, { code: "04", name: "La Habana" },
    { code: "05", name: "Matanzas" }, { code: "06", name: "Villa Clara" },
    { code: "07", name: "Cienfuegos" }, { code: "08", name: "Sancti Spíritus" },
    { code: "09", name: "Ciego de Ávila" }, { code: "10", name: "Camagüey" },
    { code: "11", name: "Las Tunas" }, { code: "12", name: "Holguín" },
    { code: "13", name: "Granma" }, { code: "14", name: "Santiago de Cuba" },
    { code: "15", name: "Guantánamo" }, { code: "99", name: "Isla de la Juventud" },
  ],
  PY_NA: [],
  IS_NA: [],
  UY_NA: [],
};

// Lookup: country code → [{ code, name }, ...]. Empty array when the country
// has no first-level subdivisions (the form falls back to a free-text input).
export function getStatesForCountryCode(countryCode) {
  return STATES_BY_COUNTRY[countryCode] || [];
}

// Lookup: country code + state code → state display name.
export function getStateName(countryCode, stateCode) {
  const states = STATES_BY_COUNTRY[countryCode] || [];
  return states.find((s) => s.code === stateCode)?.name || stateCode || "";
}